### PR TITLE
GettingStarted: Improve the wording a bit

### PR DESCRIPTION
**Pull request by sschuberth**
*Edit:* I decided to not add the result files for now but only apply the wording improvements.

### CODE REVIEW

**Comment by tsteenbe** [comment]
I propose to move the *.yml file into docs/examples as it's an example of ORT output data. Further more I would lowercase the *.yml file as we do in other places in ORT like [analyzer/src/funTest/assets/projects/external/](https://github.com/heremaps/oss-review-toolkit/tree/master/analyzer/src/funTest/assets/projects/external).

Off topic: do we have file/dir naming policy - from browsing ORT it looks like CamelCase for files and hypens for directories but we are not consitent. For docs I would prefer us to swith to hypthen to help SEO when we render a website from ORT docs in the near future.

**Comment by sschuberth** [comment]
> I also propose to lowercase the *.yml file

I wanted the files to have the same prefix as `GettingStarted.md`, but if we move them to a different directory, having the exact same prefix becomes less important anyway, so I'll rename them to `getting-started-*`.

**Comment by sschuberth** [comment]
BTW, should we also prefix the `examples/*.ort.yml` files with `excludes-*` now, to group them against the `getting-started-*` files?

**Comment by mnonnenmacher** [comment]
I would prefer to add only the evaluation result file and explain in the docs that each tool (analyzer, scanner, evaluator) adds a section to the file. Then we would only need to keep one file up to date.

And should we switch from mime-types to a sample project with far less dependencies? I think it does not help understanding the file structure to have over 200 dependencies in this file.

**Comment by sschuberth** [comment]
@mnonnenmacher, please re-review, I've dropped that part from the PR.

**Pull request merged**
