### PR TITLE
Gradle

### PR DESCRIPTION
**Pull request by mnonnenmacher**
See the individual commit messages for details.

---
This change is [Reviewable](https://reviewable.io/reviews/heremaps/oss-review-toolkit/37)

### CODE REVIEW

**Comment by sschuberth** [comment]
> Gradle: Use expression body syntax from command()

Nit: from -> for

---

Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[analyzer/src/funTest/assets/projects/synthetic/project-gradle-expected-output-app.yml, line 207 at r4](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/37#-KzSevcPBNiQCcVCUnsV:-KzSevcQaByBD5KW1CSF:b-a98ax) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/e2ecb7824fcc84bb09ec77f89f7fd9eee353705b/analyzer/src/funTest/assets/projects/synthetic/project-gradle-expected-output-app.yml#L207)):*
> ```YAML
>   version: "3.5"
>   declared_licenses:
>   - "Apache License, Version 2.0"
> ```

Note to myself: The declared license actually comes from the "grand-parent" POM!

---

*[analyzer/src/main/kotlin/managers/Gradle.kt, line 126 at r3](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/37#-KzSbmArRfQNHLL9x0t7:-KzSbmArRfQNHLL9x0t8:b-jresti) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/72b5adc5efd24116e8c1afadf9b542b279e533c6/analyzer/src/main/kotlin/managers/Gradle.kt#L126)):*
> ```Kotlin
> 
>     private fun parseDependency(dependency: Dependency, packages: MutableMap<String, Package>): PackageReference {
>         println("pomFile: ${dependency.pomFile}")
> ```

Left-over debug code?

---

*[analyzer/src/main/kotlin/managers/Gradle.kt, line 199 at r4](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/37#-KzSgX1mF5sqjfVIx3--:-KzSgX1nKlAcX6Uh9qge:bjtpa1i) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/e2ecb7824fcc84bb09ec77f89f7fd9eee353705b/analyzer/src/main/kotlin/managers/Gradle.kt#L199)):*
> inner

Is this really needed? At least it compiles also without `inner`.

---

*[analyzer/src/main/resources/init.gradle, line 136 at r3](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/37#-KzSd4Cq6qXi3cjDBjXP:-KzSd4Cq6qXi3cjDBjXQ:bbr287i) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/72b5adc5efd24116e8c1afadf9b542b279e533c6/analyzer/src/main/resources/init.gradle#L136)):*
> [0]

Maybe use `.first()` instead?

---

*[analyzer/src/main/resources/init.gradle, line 137 at r3](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/37#-KzSd8ZCmlX8ODy504nE:-KzSd8ZCmlX8ODy504nF:bbr287i) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/72b5adc5efd24116e8c1afadf9b542b279e533c6/analyzer/src/main/resources/init.gradle#L137)):*
> [0]

Maybe use `.first()` instead?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/37#-:-KzSb0x0XNHxlM9l8d0P:bxm0foh)*

**Comment by mnonnenmacher** [comment]
Done.

I have only addressed comments so far, still have to fix the tests.

---

Review status: 2 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[analyzer/src/main/kotlin/managers/Gradle.kt, line 126 at r3](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/37#-KzSbmArRfQNHLL9x0t7:-KzT9qJ9jpQPQ3reXHid:b-896fix) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/72b5adc5efd24116e8c1afadf9b542b279e533c6/analyzer/src/main/kotlin/managers/Gradle.kt#L126)):*
<details><summary><i>Previously, sschuberth (Sebastian Schuberth) wrote…</i></summary><blockquote>

Left-over debug code?
</blockquote></details>

Done.

---

*[analyzer/src/main/kotlin/managers/Gradle.kt, line 199 at r4](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/37#-KzSgX1mF5sqjfVIx3--:-KzT9rqWBe7mBb_8F8Ex:bo5v05u) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/e2ecb7824fcc84bb09ec77f89f7fd9eee353705b/analyzer/src/main/kotlin/managers/Gradle.kt#L199)):*
<details><summary><i>Previously, sschuberth (Sebastian Schuberth) wrote…</i></summary><blockquote>

> inner

Is this really needed? At least it compiles also without `inner`.
</blockquote></details>

No, done.

---

*[analyzer/src/main/resources/init.gradle, line 136 at r3](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/37#-KzSd4Cq6qXi3cjDBjXP:-KzTAFUQpA4vTTE114s8:b-896fix) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/72b5adc5efd24116e8c1afadf9b542b279e533c6/analyzer/src/main/resources/init.gradle#L136)):*
<details><summary><i>Previously, sschuberth (Sebastian Schuberth) wrote…</i></summary><blockquote>

> [0]

Maybe use `.first()` instead?
</blockquote></details>

Done.

---

*[analyzer/src/main/resources/init.gradle, line 137 at r3](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/37#-KzSd8ZCmlX8ODy504nE:-KzTAFm6r-s1-eeNlnzO:b-896fix) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/72b5adc5efd24116e8c1afadf9b542b279e533c6/analyzer/src/main/resources/init.gradle#L137)):*
<details><summary><i>Previously, sschuberth (Sebastian Schuberth) wrote…</i></summary><blockquote>

> [0]

Maybe use `.first()` instead?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/37#-:-KzT98RslX-QbdjuDfSm:b5tpuns)*

**Comment by sschuberth** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r5.
Review status: 1 of 8 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/37#-:-KzULfFGt33kTjNVkdH-:bnfp4nl)*

**Comment by sschuberth** [comment]
Reviewed 1 of 1 files at r6.
Review status: 1 of 8 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/37)*

**Comment by sschuberth** [comment]
Reviewed 2 of 2 files at r7.
Review status: 3 of 8 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/37)*

**Comment by sschuberth** [comment]
Review status: 3 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[analyzer/src/funTest/assets/projects/synthetic/project-gradle-expected-output-app.yml, line 207 at r4](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/37#-KzSevcPBNiQCcVCUnsV:-KzUM1msVRGxQ4Dm8TDe:b2nhei9) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/e2ecb7824fcc84bb09ec77f89f7fd9eee353705b/analyzer/src/funTest/assets/projects/synthetic/project-gradle-expected-output-app.yml#L207)):*
<details><summary><i>Previously, sschuberth (Sebastian Schuberth) wrote…</i></summary><blockquote>

Note to myself: The declared license actually comes from the "grand-parent" POM!
</blockquote></details>

FYI

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/37)*

**Comment by sschuberth** [comment]
Reviewed 3 of 3 files at r8.
Review status: 5 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/37)*

**Comment by sschuberth** [comment]
Reviewed 1 of 1 files at r9.
Review status: 6 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/37)*

**Comment by sschuberth** [comment]
Reviewed 2 of 2 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/37)*

**Pull request merged**
