### PR TITLE
Avoid creating temporary files for HTTP downloads

### PR DESCRIPTION
**Pull request by sschuberth**
Please have a look at the individual commit messages for the details.

---
This change is [Reviewable](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1618)

### CODE REVIEW

**Comment by sschuberth** [comment]
FYI, for some reason I was seeing "unexpected end of stream" when doing the same change in `ScanCode.kt` as in `BoyterLc.kt`, probably because of the size of the archive and some timeout issues, so I want to first see how robust this turns out to be for `BoyterLc.kt`.

**Comment by sschuberth** [comment]
@mnonnenmacher @fviernau, could you please test this on your staging instance with a larger scan before merging to be on the safe side?

**Comment by mnonnenmacher** [comment]
@sschuberth: I have rebased this change and will start some tests now. In the meantime, can you add a rationale to the commit message? Have there been issue with using temporary files, or does this improve performance?

**Comment by sschuberth** [comment]
It should improve performance due to less / no more file I/O, but I haven't measured this.

**Comment by mnonnenmacher** [comment]
I have extensively tested the ArtifactoryStorage change and it worked flawless. But I could not test the BoyterLc change because we have the `lc` command from monodevelop installed which confuses ORT. But I think this can easily be tested locally.

**Comment by sschuberth** [comment]
> I have extensively tested the ArtifactoryStorage change and it worked flawless.

Thank you! I'll rebase once your other PR with the test upgrade is merged and amend the commit messages as discussed.

> But I could not test the BoyterLc change because we have the lc command from monodevelop installed which confuses ORT. But I think this can easily be tested locally.

I had this problem in the past, too, but I thought it was solved by not only checking for the executable to be in the `PATH`, but also it to report the expected version. As Mono's `lc` reports a different version than the one we expect from Boyter's `lc`, the bootstrapping should kick in and the correct `lc` should be used. If I have some time I can look at why this apparently does not work as expected.

**Pull request merged**
