### PR TITLE
Docker improvements

### PR DESCRIPTION
**Pull request by sschuberth**
Please have a look at the individual commit messages for the details.

/cc @iamwillbar

---
This change is [Reviewable](https://reviewable.io/reviews/heremaps/oss-review-toolkit/150)

### CODE REVIEW

**Comment by sschuberth** [comment]
Please note that running scancode from the container does not work yet due to permission issues which I'm going to address soonish, but I already wanted to share what I have now. Also, some convenience scripts will be added later.

**Comment by iamwillbar** [comment]
Running `chown -R toolkit:toolkit` against the ScanCode installation directory should solve your permission issues. I noticed that ScanCode downloads additional things on first execution so I ran `scancode --version` once in my PR to bake these additional files into the image. If you do this, you need to make sure the `chown` is after doing this otherwise the newly downloaded files will have the wrong owner.

**Comment by sschuberth** [comment]
> Running `chown -R toolkit:toolkit` against the ScanCode installation directory should solve your permission issues.

Well, that would work (or passing `--chown` to `COPY`), but I'd actually prefer to do what we do for our internal Docker image currently, and run as the host's user also inside the Docker container with [this trick](https://github.com/heremaps/oss-review-toolkit/blob/docker-improvements-2/docker-run.sh#L5-L6). That way you could easily mount one of the user's directories from the host in order to scan it inside the container.

Also, I'm thinking about not copying the ORT files at all, actually, but just mount them to the container. 

@iamwillbar @mnonnenmacher Any opinions / preferences here?

**Comment by iamwillbar** [comment]
@sschuberth that change would prevent us using the image, our reasoning for creating an image was to be able to run it in a host-dependent way in places where ORT would not be on the host and we definitely wouldn't want to assume the host's identity. For example, we'd be running the container inside Kubernetes or using [Azure Container Instances](https://azure.microsoft.com/en-us/services/container-instances/).

@jeffmcaffer and I were able to mount source from the host into the container for scanning and producing the outputs without permission issues on OSX and Windows. We did have a permission issue before I added the `chown` step.

**Comment by sschuberth** [comment]
@iamwillbar Ok, understood. Another thought: Should we only put the ORT binaries into the container then? Not copying all the sources and test assets, but only the required JARs / scripts would also safe some time building the container. Even if you probably don't do it that often.

**Comment by iamwillbar** [comment]
Yes, that would be ideal. Did you want to do that or point me at what
should be copied and I'll make the changes?

**Comment by sschuberth** [comment]
I'll do that.

**Comment by mnonnenmacher** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, 1 of 1 files at r9, 1 of 1 files at r10, 1 of 1 files at r11, 1 of 1 files at r12, 1 of 1 files at r13.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/150)*

**Pull request merged**
