### PR TITLE
GitRepo: Revert to using the latest stable version again

### PR DESCRIPTION
**Pull request by fviernau**

### CODE REVIEW

**Comment by sschuberth** [comment]
@fviernau I'm going to rebase this!

**Comment by sschuberth** [comment]
Interestingly, we now have a diff in manifest paths, but only on Windows: `path: "manifest.xml"` vs. `"../manifest.xml"`. I'll try to find the time to look into it.

**Comment by fviernau** [comment]
> @fviernau I'm going to rebase this!

Sure. Thanks for helping with this @sschuberth! So feel free to do whatever you want to this PR.

**Comment by sschuberth** [comment]
This indeed requires more work as it turns out that manifest.xml now intentionally is a copy instead of a link, which means we cannot determine the original manifest name anymore by resolving the link. As such it is probably the best to stick with repo-1.

**Comment by fviernau** [comment]
Thanks @sschuberth for taking this over and solving it, appreciated!

**Pull request merged**
