### PR TITLE
Implement guessing of VCS revisions based on package versions

### PR DESCRIPTION
**Pull request by sschuberth**
Please have a look at the individual commit messages for the details.

/cc @jeffmcaffer @iamwillbar 

---
This change is [Reviewable](https://reviewable.io/reviews/heremaps/oss-review-toolkit/189)

### CODE REVIEW

**Comment by mnonnenmacher** [comment]
Reviewed 4 of 4 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 2 of 2 files at r6, 2 of 2 files at r7, 1 of 1 files at r8, 1 of 1 files at r9, 1 of 1 files at r10.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[downloader/src/funTest/kotlin/GitTest.kt, line 71 at r5](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/189#-L2X3TCied2MylJuF5rC:-L2X3TCjohn-XhUNqLLH:b11b5g3) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/cb4d2fb8bc2132d0bef45c89039a29512250d07f/downloader/src/funTest/kotlin/GitTest.kt#L71)):*
> ```Kotlin
>             )
>             val actualFiles = workingTree.workingDir.list()
>             actualFiles.joinToString("\n") shouldBe expectedFiles.joinToString("\n")
> ```

AAA pattern?

---

*[downloader/src/funTest/kotlin/MercurialTest.kt, line 72 at r10](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/189#-L2X6SqtO3qhrx98oO8U:-L2X6SqtO3qhrx98oO8V:b11b5g3) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/63cab251b578ebfb1cc3ee27d9ab2c354767169f/downloader/src/funTest/kotlin/MercurialTest.kt#L72)):*
> ```Kotlin
>             )
>             val actualFiles = workingTree.workingDir.list()
>             actualFiles.joinToString("\n") shouldBe expectedFiles.joinToString("\n")
> ```

AAA pattern?

---

*[downloader/src/funTest/kotlin/SubversionTest.kt, line 68 at r3](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/189#-L2WxbUplejFZM9tEinC:-L2WxbUplejFZM9tEinD:b1svuj5) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/78fede0d0c14487b68799083f85b3a2f67850938/downloader/src/funTest/kotlin/SubversionTest.kt#L68)):*
> ```Kotlin
>             )
>             val actualFiles = workingTree.workingDir.list()
>             actualFiles.joinToString("\n") shouldBe expectedFiles.joinToString("\n")
> ```

For the arrange, act, assert pattern this should be reordered, also maybe check the working tree for validity:
```
val vcs = ...
val expectedFiles = ...

val workingTree = Subversion.download...

workingTree.isValid() shouldBe true
workingTree.getRevision() shouldBe ...
workingTree.workingDir...
```

---

*[downloader/src/main/kotlin/VersionControlSystem.kt, line 191 at r1](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/189#-L2WuKQGWEDGTj79ZxcZ:-L2WuKQHc34gS1LDaycg:b11d946) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/fb4f4a779184aefd9286ce96c224edbdf0717a1b/downloader/src/main/kotlin/VersionControlSystem.kt#L191)):*
> ```Kotlin
>         /**
>          * Search (symbolic) names of VCS revisions for matches with the given version.
>          */
> ```

Add `@return A matching VCS revision or an empty String if no match is found.`.

---

*[downloader/src/main/kotlin/VersionControlSystem.kt, line 203 at r1](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/189#-L2Wv0_ToMixTaFvzEXz:-L2Wv0_ToMixTaFvzEY-:b-6w6xyf) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/fb4f4a779184aefd9286ce96c224edbdf0717a1b/downloader/src/main/kotlin/VersionControlSystem.kt#L203)):*
> version

---

*[downloader/src/main/kotlin/VersionControlSystem.kt, line 204 at r1](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/189#-L2WvP_rGWon5uscp4Bo:-L2WvP_rGWon5uscp4Bp:bmqk9r) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/fb4f4a779184aefd9286ce96c224edbdf0717a1b/downloader/src/main/kotlin/VersionControlSystem.kt#L204)):*
> ```Kotlin
> 
>             // For now, only consider tag names.
>             val candidates = listRemoteTags().filter { name ->
> ```

Maybe call it tag instead of name?

---

*[downloader/src/main/kotlin/VersionControlSystem.kt, line 205 at r1](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/189#-L2Wv21znRBFJpGSdhXZ:-L2Wv21znRBFJpGSdhX_:bx3jjvl) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/fb4f4a779184aefd9286ce96c224edbdf0717a1b/downloader/src/main/kotlin/VersionControlSystem.kt#L205)):*
> ```Kotlin
>             // For now, only consider tag names.
>             val candidates = listRemoteTags().filter { name ->
>                 variants.any { version ->
> ```

Better call it "variant" than "version", this doesn't hide the function parameter. Also it's the singular of the collection name which is a good practice.

---

*[downloader/src/main/kotlin/vcs/Git.kt, line 145 at r4](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/189#-L2X2hApt0BH7DvqXosp:-L2X2hAqzB28p868xtno:baxqcuq) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/81b5f5b6b4f0470053ca966ef06c55579d0b28ae/downloader/src/main/kotlin/vcs/Git.kt#L145)):*
> ```Kotlin
>             }
> 
>             throw DownloadException("Could not checkout ${vcs.url}.", e)
> ```

I guess this renaming could be confusing, as the IOException could be caused by the fetch operation, not the checkout.

---

*[downloader/src/main/kotlin/vcs/Mercurial.kt, line 129 at r9](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/189#-L2X4x06CGGFpcPRHZNI:-L2X4x07Cfkg_38PIBvs:bdq627) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/aa9965cfe9f282604484aa71b0a908b4fa6e17cb/downloader/src/main/kotlin/vcs/Mercurial.kt#L129)):*
> ```Kotlin
> 
>             // Update the working tree to the desired revision. Do not do that via "-u" passed to "pull" to update in
>             // any case and not only if new changesets were pulled.
> ```

I found this hard to understand, consider rephrasing to explain why it is done the way it is, not why it is not done in a different way.
Would a Mercurial user usually expect a `pull -u`here and be surprised about the `update`?

---

*[downloader/src/main/kotlin/vcs/Mercurial.kt, line 138 at r9](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/189#-L2X5dM8CCFff8eOWCRJ:-L2X5dM998YAqp1_vCv0:bf6o1x4) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/aa9965cfe9f282604484aa71b0a908b4fa6e17cb/downloader/src/main/kotlin/vcs/Mercurial.kt#L138)):*
> ```Kotlin
>             }
> 
>             throw DownloadException("Could not checkout ${vcs.url}.", e)
> ```

Maybe we should use 'check out' (with a space) here and in the other VCS classes to make clear we do not refer to a command, because otherwise 'checkout' has a different meaning in english. Or just say 'download'?

---

*[downloader/src/test/kotlin/SubversionTest.kt, line 111 at r1](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/189#-L2WvlDzinUqECEoX7sQ:-L2WvlDzinUqECEoX7sR:bkdury0) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/fb4f4a779184aefd9286ce96c224edbdf0717a1b/downloader/src/test/kotlin/SubversionTest.kt#L111)):*
> ```Kotlin
>             workingTree.guessRevisionNameForVersion("0.3.9") shouldBe "docutils-0.3.9"
>             workingTree.guessRevisionNameForVersion("0.3.10") shouldBe "prest-0.3.10"
>             workingTree.guessRevisionNameForVersion("") shouldBe ""
> ```

In the other tests you also search for a non-existent version, consider doing the same here for consistency.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/189)*

**Comment by sschuberth** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[downloader/src/main/kotlin/VersionControlSystem.kt, line 191 at r1](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/189#-L2WuKQGWEDGTj79ZxcZ:-L2ZF__378hnMVdxqKj5:b-896fix) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/fb4f4a779184aefd9286ce96c224edbdf0717a1b/downloader/src/main/kotlin/VersionControlSystem.kt#L191)):*
<details><summary><i>Previously, mnonnenmacher (Martin Nonnenmacher) wrote…</i></summary><blockquote>

Add `@return A matching VCS revision or an empty String if no match is found.`.
</blockquote></details>

Done.

---

*[downloader/src/main/kotlin/VersionControlSystem.kt, line 203 at r1](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/189#-L2Wv0_ToMixTaFvzEXz:-L2ZFg1ygdMHJWPCRYmC:b-lk2847) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/fb4f4a779184aefd9286ce96c224edbdf0717a1b/downloader/src/main/kotlin/VersionControlSystem.kt#L203)):*
<details><summary><i>Previously, mnonnenmacher (Martin Nonnenmacher) wrote…</i></summary><blockquote>

> version
</blockquote></details>

Do you mean I should say "consider version names"? Because that's not true. What I want to say is that we only consider names of tags when searching for matches of versions. We're not considering branch names, for example.

---

*[downloader/src/main/kotlin/VersionControlSystem.kt, line 204 at r1](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/189#-L2WvP_rGWon5uscp4Bo:-L2ZGMxTsjXOHUXkvwcF:b-p55i0r) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/fb4f4a779184aefd9286ce96c224edbdf0717a1b/downloader/src/main/kotlin/VersionControlSystem.kt#L204)):*
<details><summary><i>Previously, mnonnenmacher (Martin Nonnenmacher) wrote…</i></summary><blockquote>

Maybe call it tag instead of name?
</blockquote></details>

Done. (Well, I went for `tagName` in the end after reading your comment below.)

---

*[downloader/src/main/kotlin/VersionControlSystem.kt, line 205 at r1](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/189#-L2Wv21znRBFJpGSdhXZ:-L2ZGvkzJEeFZ5zMp1vm:b58rgi5) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/fb4f4a779184aefd9286ce96c224edbdf0717a1b/downloader/src/main/kotlin/VersionControlSystem.kt#L205)):*
<details><summary><i>Previously, mnonnenmacher (Martin Nonnenmacher) wrote…</i></summary><blockquote>

Better call it "variant" than "version", this doesn't hide the function parameter. Also it's the singular of the collection name which is a good practice.
</blockquote></details>

I decided to instead rename `variants` to `versionNames` and use a singular `versionName` here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/189)*

**Comment by sschuberth** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[downloader/src/test/kotlin/SubversionTest.kt, line 111 at r1](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/189#-L2WvlDzinUqECEoX7sQ:-L2ZI9Gs4lowsDPpvPaK:b-896fix) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/fb4f4a779184aefd9286ce96c224edbdf0717a1b/downloader/src/test/kotlin/SubversionTest.kt#L111)):*
<details><summary><i>Previously, mnonnenmacher (Martin Nonnenmacher) wrote…</i></summary><blockquote>

In the other tests you also search for a non-existent version, consider doing the same here for consistency.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/189)*

**Comment by sschuberth** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[downloader/src/funTest/kotlin/SubversionTest.kt, line 68 at r3](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/189#-L2WxbUplejFZM9tEinC:-L2ZLTqUSh70KH3tHeXP:b-mlxcnp) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/78fede0d0c14487b68799083f85b3a2f67850938/downloader/src/funTest/kotlin/SubversionTest.kt#L68)):*
> arrange, act, assert pattern

To be honest, I'm not a big fan of this pattern as it violates another more important pattern for me: To declare variables close to where they are first used. But done anyway as there is little code in general, and as the AAA patterns helps to identify tests that should be split into multiple tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/189)*

**Comment by sschuberth** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[downloader/src/funTest/kotlin/GitTest.kt, line 71 at r5](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/189#-L2X3TCied2MylJuF5rC:-L2ZNi_uRwwm0DhsL5n3:b-896fix) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/cb4d2fb8bc2132d0bef45c89039a29512250d07f/downloader/src/funTest/kotlin/GitTest.kt#L71)):*
<details><summary><i>Previously, mnonnenmacher (Martin Nonnenmacher) wrote…</i></summary><blockquote>

AAA pattern?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/189)*

**Comment by sschuberth** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[downloader/src/funTest/kotlin/MercurialTest.kt, line 72 at r10](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/189#-L2X6SqtO3qhrx98oO8U:-L2ZNmmWvoKbfyGAD2Yb:b-896fix) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/63cab251b578ebfb1cc3ee27d9ab2c354767169f/downloader/src/funTest/kotlin/MercurialTest.kt#L72)):*
<details><summary><i>Previously, mnonnenmacher (Martin Nonnenmacher) wrote…</i></summary><blockquote>

AAA pattern?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/189)*

**Comment by sschuberth** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[downloader/src/main/kotlin/vcs/Git.kt, line 145 at r4](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/189#-L2X2hApt0BH7DvqXosp:-L2ZOSlAkDuiWpBj7BPZ:b-t3pkcl) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/81b5f5b6b4f0470053ca966ef06c55579d0b28ae/downloader/src/main/kotlin/vcs/Git.kt#L145)):*
<details><summary><i>Previously, mnonnenmacher (Martin Nonnenmacher) wrote…</i></summary><blockquote>

I guess this renaming could be confusing, as the IOException could be caused by the fetch operation, not the checkout.
</blockquote></details>

In fact, it *could* be caused by any Git command, also `init` or `config`. I'll align on a more generic wording that does not use any VCS-specific terms.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/189)*

**Comment by sschuberth** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[downloader/src/main/kotlin/vcs/Mercurial.kt, line 129 at r9](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/189#-L2X4x06CGGFpcPRHZNI:-L2ZPlE4SCaDaCa8Avrh:b-6q9qli) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/aa9965cfe9f282604484aa71b0a908b4fa6e17cb/downloader/src/main/kotlin/vcs/Mercurial.kt#L129)):*
<details><summary><i>Previously, mnonnenmacher (Martin Nonnenmacher) wrote…</i></summary><blockquote>

I found this hard to understand, consider rephrasing to explain why it is done the way it is, not why it is not done in a different way.
Would a Mercurial user usually expect a `pull -u`here and be surprised about the `update`?
</blockquote></details>

Usually, a Mercurial user would probably indeed update the working tree at the same time as pulling changes, via `pull -u`. However, as `hg pull --help` explains, "[-u does only] update to new branch head if changesets were pulled". That is, if you already happen to have the requested revision locally, nothing is pulled, and the working tree is not updated to the requested revision but stays at whatever revision it currently is at. That's not what we want, obviously, and hence we need to do an explicit update separately. I'll try to improve the wording, but still be less exhaustive than this comment :wink:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/189)*

**Comment by mnonnenmacher** [comment]
Reviewed 2 of 9 files at r11, 1 of 1 files at r12, 1 of 1 files at r13, 1 of 1 files at r14, 1 of 1 files at r15, 1 of 2 files at r17, 1 of 1 files at r19, 1 of 1 files at r20.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[downloader/src/main/kotlin/VersionControlSystem.kt, line 203 at r1](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/189#-L2Wv0_ToMixTaFvzEXz:-L2ZpE8Ct_YcZJTZM9zI:bak29x8) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/fb4f4a779184aefd9286ce96c224edbdf0717a1b/downloader/src/main/kotlin/VersionControlSystem.kt#L203)):*
<details><summary><i>Previously, sschuberth (Sebastian Schuberth) wrote…</i></summary><blockquote>

Do you mean I should say "consider version names"? Because that's not true. What I want to say is that we only consider names of tags when searching for matches of versions. We're not considering branch names, for example.
</blockquote></details>

Sorry, this comment was unintended.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/189)*

**Pull request merged**
