### PR TITLE
Remove deprecated copyright deserialization

### PR DESCRIPTION
**Pull request by fviernau**

### CODE REVIEW

**Comment by sschuberth** [comment]
Something seems to be wrong with GitHub again... the UI shows me 2 commmits in this PR, although I believe it should be 4.

**Comment by mnonnenmacher** [comment]
> Something seems to be wrong with GitHub again... the UI shows me 2 commits in this PR, although I believe it should be 4.

I think it's correct, `git log master..remove-deprecated-copyright-deserialization` shows me only the two commits.

**Comment by sschuberth** [comment]
@mnonnenmacher are you sure your local branch of `remove-deprecated-copyright-deserialization` is up-to-date? Try with `origin/remove-deprecated-copyright-deserialization` (after fetching).

**Comment by sschuberth** [comment]
Also, I see changes e.g. in `reporter/src/funTest/assets/static-html-reporter-test-input.yml`, whereas I though this should only contain the cherry-picked 70e421b2cec09896f2b505a970a18ac551709e58 and  01a0ec76887e19c66a9ea8f2cab01140994c4d1c. I'm confused...

**Comment by mnonnenmacher** [comment]
Yes, my branch is up-to-date. The static-html-reporter-test-input change is part of 2223b57 which is not one of the two commits you mention.

**Comment by fviernau** [comment]
Force pushed again, in the GH UI i can see the diffs of the most recent version of the (2) commits. Hope it works for you as well.

**Pull request merged**
