### PR TITLE
Merge analyzer result into single YAML

### PR DESCRIPTION
**Pull request by pnowakowski**
This change is [Reviewable](https://reviewable.io/reviews/heremaps/oss-review-toolkit/258)

### CODE REVIEW

**Comment by mnonnenmacher** [comment]
Review status: 0 of 5 files reviewed at latest revision, 15 unresolved discussions.

---

*[analyzer/src/funTest/kotlin/MainTest.kt, line 137 at r1](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/258#-L4155kTuoKlejQNuaKU:-L4155kTuoKlejQNuaKV:baav5p0) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/b678e60976c0f1de389b39d383616f0521071c73/analyzer/src/funTest/kotlin/MainTest.kt#L137)):*
> ```Kotlin
>                     expectedResultTree["project_id_result_file_path_map"].asIterable().count()
>             resultTree["packages"] shouldBe expectedResultTree["packages"]
>         }.config(tags = setOf(ExpensiveTag))
> ```

I'd like to have additional unit tests for the MergedResultsBuilder without the ExpensiveTag in a separate test class (not funTest).

---

*[analyzer/src/main/kotlin/Main.kt, line 91 at r1](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/258#-L410RIGJAbJbi2RlBfr:-L410RIGJAbJbi2RlBfs:b-jsylan) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/b678e60976c0f1de389b39d383616f0521071c73/analyzer/src/main/kotlin/Main.kt#L91)):*
> ```Kotlin
> 
>     @Parameter(description = "Merge all results into additional single result file. NOTE: original result files for " +
>             "all build files are kept along.",
> ```

"Merge all scan results into a single results file. The individual scan results files for each build file are kept will still be created."

---

*[analyzer/src/main/kotlin/Main.kt, line 232 at r1](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/258#-L4118Rx-WHOT8HeV0Qu:-L4118Rx-WHOT8HeV0Qv:beeq8f4) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/b678e60976c0f1de389b39d383616f0521071c73/analyzer/src/main/kotlin/Main.kt#L232)):*
> ```Kotlin
> 
>             if (createMergedResult) {
>                 println("Merged result not created (nothing to merge).")
> ```

"results" (we mostly use the plural elsewhere)

---

*[analyzer/src/main/kotlin/Main.kt, line 299 at r1](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/258#-L414kEkFfSgPjuB1PBM:-L414kElDXVWBs3dBRAR:b-epzmz3) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/b678e60976c0f1de389b39d383616f0521071c73/analyzer/src/main/kotlin/Main.kt#L299)):*
> ```Kotlin
> 
>             println("Writing merged results\nto\n\t$outputFile")
>             println("map size: ${it.projectIdResultFilePathMap.size}")
> ```

Leftover debug output?

---

*[model/src/main/kotlin/MergedAnalyzerResult.kt, line 22 at r1](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/258#-L411PCGjeUdYAnGER5_:-L411PCGjeUdYAnGER5a:b7goi1d) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/b678e60976c0f1de389b39d383616f0521071c73/model/src/main/kotlin/MergedAnalyzerResult.kt#L22)):*
> ```Kotlin
> package com.here.ort.model
> 
> import com.fasterxml.jackson.annotation.JsonProperty
> ```

Add an empty line between the imports.

---

*[model/src/main/kotlin/MergedAnalyzerResult.kt, line 49 at r1](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/258#-L411hmEGnCH-OI-6asg:-L411hmEGnCH-OI-6ash:b-gb6lro) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/b678e60976c0f1de389b39d383616f0521071c73/model/src/main/kotlin/MergedAnalyzerResult.kt#L49)):*
> ```Kotlin
> 
>         /**
>          * Map holding paths to individual analyzer results for each  project.
> ```

* ...to the individual...
* Double space after each.

---

*[model/src/main/kotlin/MergedAnalyzerResult.kt, line 52 at r1](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/258#-L412QfOhUOUUNkWuDnG:-L412QfOhUOUUNkWuDnH:b-fm3se6) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/b678e60976c0f1de389b39d383616f0521071c73/model/src/main/kotlin/MergedAnalyzerResult.kt#L52)):*
> ```Kotlin
>          */
>         @JsonProperty("project_id_result_file_path_map")
>         val projectIdResultFilePathMap: Map<Identifier, String>,
> ```

I would call it `projectResultsFiles`.

---

*[model/src/main/kotlin/MergedAnalyzerResult.kt, line 55 at r1](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/258#-L412cqkYy2bSjT0owdD:-L412cqkYy2bSjT0owdE:b-8y0yto) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/b678e60976c0f1de389b39d383616f0521071c73/model/src/main/kotlin/MergedAnalyzerResult.kt#L55)):*
> ```Kotlin
> 
>         /**
>          * The set of identified packages used by all found projects.
> ```

...packages for all projects.

---

*[model/src/main/kotlin/MergedAnalyzerResult.kt, line 60 at r1](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/258#-L4132xDtXLfWLLZ7ovc:-L4132xDtXLfWLLZ7ovd:b-wl9sqc) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/b678e60976c0f1de389b39d383616f0521071c73/model/src/main/kotlin/MergedAnalyzerResult.kt#L60)):*
> ```Kotlin
> )
> 
> class MergedResultsBuilder(private val allowDynamicVersions: Boolean, private val repoDetails:
> ```

Should be "directoryDetails" to match the class name.

---

*[model/src/main/kotlin/MergedAnalyzerResult.kt, line 61 at r1](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/258#-L412oH9x-Xj_inF9vPI:-L412oH9x-Xj_inF9vPJ:bqleube) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/b678e60976c0f1de389b39d383616f0521071c73/model/src/main/kotlin/MergedAnalyzerResult.kt#L61)):*
> ```Kotlin
> 
> class MergedResultsBuilder(private val allowDynamicVersions: Boolean, private val repoDetails:
> ScannedDirectoryDetails) {
> ```

Please format the parameters as you do for ScannedDirectoryDetails below (one param per line) for consistency.

---

*[model/src/main/kotlin/MergedAnalyzerResult.kt, line 64 at r1](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/258#-L413ODed8g4S7eoGklo:-L413ODed8g4S7eoGklp:b-isnbkh) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/b678e60976c0f1de389b39d383616f0521071c73/model/src/main/kotlin/MergedAnalyzerResult.kt#L64)):*
> ```Kotlin
> 
>     private val projects = mutableSetOf<Project>()
>     private val projectIdResultFilePathMap = mutableMapOf<Identifier, String>()
> ```

Same renaming as above.

---

*[model/src/main/kotlin/MergedAnalyzerResult.kt, line 71 at r1](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/258#-L413diWg4gdtsuFZ4hI:-L413diWg4gdtsuFZ4hJ:b-1xd9bb) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/b678e60976c0f1de389b39d383616f0521071c73/model/src/main/kotlin/MergedAnalyzerResult.kt#L71)):*
> ```Kotlin
>                     packages.toSortedSet())
> 
>     fun addResult(absoluteOutputPath: String, analyzerResult: AnalyzerResult) {
> ```

Maybe "analyzerResultPath".

---

*[model/src/main/kotlin/MergedAnalyzerResult.kt, line 88 at r1](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/258#-L413jS_r3UVd6EnzksV:-L413jS_r3UVd6EnzksW:b-3v878k) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/b678e60976c0f1de389b39d383616f0521071c73/model/src/main/kotlin/MergedAnalyzerResult.kt#L88)):*
> ```Kotlin
>          * Full path of analyzed directory
>          */
>         val path: String,
> ```

Add an empty line after this one.

---

*[model/src/main/kotlin/MergedAnalyzerResult.kt, line 95 at r1](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/258#-L413rPJc41abUjzL-t3:-L413rPJc41abUjzL-t4:b9vgcyv) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/b678e60976c0f1de389b39d383616f0521071c73/model/src/main/kotlin/MergedAnalyzerResult.kt#L95)):*
> ```Kotlin
> 
>         /**
>          * Processed VCS-related information about the [Project] that has e.g. common mistakes corrected.
> ```

```
Normalized [VcsInfo] of the analyzed [Project].

@see [VcsInfo.normalize]
```

---

*[model/src/main/kotlin/Project.kt, line 86 at r1](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/258#-L414JgmJmIG3bYR4l4z:-L414JgmJmIG3bYR4l5-:b-cvujkm) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/b678e60976c0f1de389b39d383616f0521071c73/model/src/main/kotlin/Project.kt#L86)):*
> ```Kotlin
> 
>     /**
>      * A comparison function to sort packages by their identifier.
> ```

Replace "packages" with "projects".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/258)*

**Comment by mnonnenmacher** [comment]
Please add a short description to the commit message with a bit more details than the title. It also works for JSON, so better say "analyzer: Add paramter to merge the results into a single file" in the title.

---

Review status: 0 of 5 files reviewed at latest revision, 15 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/258#-:-L415aupZOtMKbDy9kbT:b-cfhoue)*

**Comment by pnowakowski** [comment]
Done.

---

Review status: 0 of 6 files reviewed at latest revision, 15 unresolved discussions.

---

*[analyzer/src/funTest/kotlin/MainTest.kt, line 137 at r1](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/258#-L4155kTuoKlejQNuaKU:-L45dDojxsyMk6LaTtIf:b-896fix) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/b678e60976c0f1de389b39d383616f0521071c73/analyzer/src/funTest/kotlin/MainTest.kt#L137)):*
<details><summary><i>Previously, mnonnenmacher (Martin Nonnenmacher) wrote…</i></summary><blockquote>

I'd like to have additional unit tests for the MergedResultsBuilder without the ExpensiveTag in a separate test class (not funTest).
</blockquote></details>

Done.

---

*[analyzer/src/main/kotlin/Main.kt, line 91 at r1](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/258#-L410RIGJAbJbi2RlBfr:-L45MqXZd_ysoP9pKi0a:b-896fix) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/b678e60976c0f1de389b39d383616f0521071c73/analyzer/src/main/kotlin/Main.kt#L91)):*
<details><summary><i>Previously, mnonnenmacher (Martin Nonnenmacher) wrote…</i></summary><blockquote>

"Merge all scan results into a single results file. The individual scan results files for each build file are kept will still be created."
</blockquote></details>

Done.

---

*[analyzer/src/main/kotlin/Main.kt, line 232 at r1](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/258#-L4118Rx-WHOT8HeV0Qu:-L45Mpyodm1kEfQrLkfR:b-896fix) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/b678e60976c0f1de389b39d383616f0521071c73/analyzer/src/main/kotlin/Main.kt#L232)):*
<details><summary><i>Previously, mnonnenmacher (Martin Nonnenmacher) wrote…</i></summary><blockquote>

"results" (we mostly use the plural elsewhere)
</blockquote></details>

Done.

---

*[analyzer/src/main/kotlin/Main.kt, line 299 at r1](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/258#-L414kEkFfSgPjuB1PBM:-L45N0iiVRbZRH1oUPyZ:b-wx4ria) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/b678e60976c0f1de389b39d383616f0521071c73/analyzer/src/main/kotlin/Main.kt#L299)):*
<details><summary><i>Previously, mnonnenmacher (Martin Nonnenmacher) wrote…</i></summary><blockquote>

Leftover debug output?
</blockquote></details>

yep :) removed.

---

*[model/src/main/kotlin/MergedAnalyzerResult.kt, line 22 at r1](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/258#-L411PCGjeUdYAnGER5_:-L45NJjqd6Z3LOlCrmCr:b-896fix) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/b678e60976c0f1de389b39d383616f0521071c73/model/src/main/kotlin/MergedAnalyzerResult.kt#L22)):*
<details><summary><i>Previously, mnonnenmacher (Martin Nonnenmacher) wrote…</i></summary><blockquote>

Add an empty line between the imports.
</blockquote></details>

Done.

---

*[model/src/main/kotlin/MergedAnalyzerResult.kt, line 49 at r1](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/258#-L411hmEGnCH-OI-6asg:-L45NPa8IEGXHoSFOznD:b-896fix) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/b678e60976c0f1de389b39d383616f0521071c73/model/src/main/kotlin/MergedAnalyzerResult.kt#L49)):*
<details><summary><i>Previously, mnonnenmacher (Martin Nonnenmacher) wrote…</i></summary><blockquote>

* ...to the individual...
* Double space after each.
</blockquote></details>

Done.

---

*[model/src/main/kotlin/MergedAnalyzerResult.kt, line 52 at r1](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/258#-L412QfOhUOUUNkWuDnG:-L45NShJ64JE1X1gpRj8:b-896fix) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/b678e60976c0f1de389b39d383616f0521071c73/model/src/main/kotlin/MergedAnalyzerResult.kt#L52)):*
<details><summary><i>Previously, mnonnenmacher (Martin Nonnenmacher) wrote…</i></summary><blockquote>

I would call it `projectResultsFiles`.
</blockquote></details>

Done.

---

*[model/src/main/kotlin/MergedAnalyzerResult.kt, line 55 at r1](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/258#-L412cqkYy2bSjT0owdD:-L45Na6tiLo4NS8byYG4:b-896fix) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/b678e60976c0f1de389b39d383616f0521071c73/model/src/main/kotlin/MergedAnalyzerResult.kt#L55)):*
<details><summary><i>Previously, mnonnenmacher (Martin Nonnenmacher) wrote…</i></summary><blockquote>

...packages for all projects.
</blockquote></details>

Done.

---

*[model/src/main/kotlin/MergedAnalyzerResult.kt, line 60 at r1](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/258#-L4132xDtXLfWLLZ7ovc:-L45Nj0GOYbSleZOqVFe:b-896fix) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/b678e60976c0f1de389b39d383616f0521071c73/model/src/main/kotlin/MergedAnalyzerResult.kt#L60)):*
<details><summary><i>Previously, mnonnenmacher (Martin Nonnenmacher) wrote…</i></summary><blockquote>

Should be "directoryDetails" to match the class name.
</blockquote></details>

Done.

---

*[model/src/main/kotlin/MergedAnalyzerResult.kt, line 61 at r1](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/258#-L412oH9x-Xj_inF9vPI:-L45Nzacky_Xy-4DZtEu:b-896fix) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/b678e60976c0f1de389b39d383616f0521071c73/model/src/main/kotlin/MergedAnalyzerResult.kt#L61)):*
<details><summary><i>Previously, mnonnenmacher (Martin Nonnenmacher) wrote…</i></summary><blockquote>

Please format the parameters as you do for ScannedDirectoryDetails below (one param per line) for consistency.
</blockquote></details>

Done.

---

*[model/src/main/kotlin/MergedAnalyzerResult.kt, line 64 at r1](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/258#-L413ODed8g4S7eoGklo:-L45OAGnVIkUMJifx-DK:b-896fix) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/b678e60976c0f1de389b39d383616f0521071c73/model/src/main/kotlin/MergedAnalyzerResult.kt#L64)):*
<details><summary><i>Previously, mnonnenmacher (Martin Nonnenmacher) wrote…</i></summary><blockquote>

Same renaming as above.
</blockquote></details>

Done.

---

*[model/src/main/kotlin/MergedAnalyzerResult.kt, line 71 at r1](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/258#-L413diWg4gdtsuFZ4hI:-L45OG7WXelaV7f8dJg-:b-896fix) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/b678e60976c0f1de389b39d383616f0521071c73/model/src/main/kotlin/MergedAnalyzerResult.kt#L71)):*
<details><summary><i>Previously, mnonnenmacher (Martin Nonnenmacher) wrote…</i></summary><blockquote>

Maybe "analyzerResultPath".
</blockquote></details>

Done.

---

*[model/src/main/kotlin/MergedAnalyzerResult.kt, line 88 at r1](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/258#-L413jS_r3UVd6EnzksV:-L45OMAguUVP9nAd7fJA:b-896fix) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/b678e60976c0f1de389b39d383616f0521071c73/model/src/main/kotlin/MergedAnalyzerResult.kt#L88)):*
<details><summary><i>Previously, mnonnenmacher (Martin Nonnenmacher) wrote…</i></summary><blockquote>

Add an empty line after this one.
</blockquote></details>

Done.

---

*[model/src/main/kotlin/MergedAnalyzerResult.kt, line 95 at r1](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/258#-L413rPJc41abUjzL-t3:-L45O_CYzVOxQ2766zme:b-896fix) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/b678e60976c0f1de389b39d383616f0521071c73/model/src/main/kotlin/MergedAnalyzerResult.kt#L95)):*
<details><summary><i>Previously, mnonnenmacher (Martin Nonnenmacher) wrote…</i></summary><blockquote>

```
Normalized [VcsInfo] of the analyzed [Project].

@see [VcsInfo.normalize]
```

</blockquote></details>

Done.

---

*[model/src/main/kotlin/Project.kt, line 86 at r1](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/258#-L414JgmJmIG3bYR4l4z:-L45OjIL4-0Jtj_oEDh3:b-896fix) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/b678e60976c0f1de389b39d383616f0521071c73/model/src/main/kotlin/Project.kt#L86)):*
<details><summary><i>Previously, mnonnenmacher (Martin Nonnenmacher) wrote…</i></summary><blockquote>

Replace "packages" with "projects".
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/258#-:-L45PnZgWSfuA5iU-yex:b-896fix)*

**Comment by mnonnenmacher** [comment]
Reviewed 5 of 5 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/258)*

**Pull request merged**
