### PR TITLE
model: Also output the package URL (purl) in addition to coordinates

### PR DESCRIPTION
**Pull request by sschuberth**
As requested by @tsteenbe. See the currently failing tests for differences in the output.

---
This change is [Reviewable](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1279)

### CODE REVIEW

**Comment by sschuberth** [comment]
Closing this in favor of trying out GitHub's new draft pull-requests.

**Comment by sschuberth** [comment]
Damn, [draft pull-requests](https://help.github.com/articles/about-pull-requests/#draft-pull-requests) are not available in the public GitHub instance.

**Comment by sschuberth** [comment]
@neubs-bsi, is this PR something that would help adoption from your side? I.e. does it add convenience for you if `purl` was part of the output, even though it could be somewhat easily constructed from the other fields already?

**Comment by neubs-bsi** [comment]
@sschuberth This could be of potential use. We will discuss this possibility internally.

**Pull request merged**
