### PR TITLE
Add a package manager implementation for Go dep

### PR DESCRIPTION
**Pull request by haikoschol**
This addresses #91 in a roundabout way, using the import feature of [dep](https://github.com/golang/dep).

The name `GoDep` is bad because it sounds like [godep](https://github.com/tools/godep) when it actually is [dep](https://github.com/golang/dep). But `Dep` is also bad because it is very generic. I don't have a strong opinion on this.

I could not find a way to avoid copying the project to a temporary directory. It needs to be inside a `GOPATH` and a `GOPATH` mandates all code to be in a directory called `src`. Plus running `dep ensure`/`dep init` and `go get` downloads lots of files to various locations, which would be harder to clean up individually than `node_modules` or a virtualenv. Speaking of, downloading everything multiple times is really ugly and slow. Maybe we can keep `GOPATH` around in between scans.

`dep` *also* maintains a cache (in `$GOPATH/pkg/dep/sources`) and unlike the content it downloads to `vendor`, it preserves the VCS files there. Using the cache would remove the need to run `go get` with every dependency, just to get the VCS URL. But the location and structure of the cache is an implementation detail of `dep`. Seems brittle to rely on that. :-/

Currently only import from [Glide](https://github.com/Masterminds/glide) and [godep](https://github.com/tools/godep) is implemented. I propose we add the others only when needed. There is some duplication of filenames in the code that I would like to get rid of. Suggestions welcome. :)

---
This change is [Reviewable](https://reviewable.io/reviews/heremaps/oss-review-toolkit/442)

### CODE REVIEW

**Comment by sschuberth** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 3 of 4 files at r3.
Review status: 2 of 17 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[utils/src/main/kotlin/ProcessCapture.kt, line 36 at r1](https://beta.reviewable.io/reviews/heremaps/oss-review-toolkit/442#-L8bfbYB2N4L52aFEbC4:-L8bfbYB2N4L52aFEbC5:b7ouz9c) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/8363f753f0ad97e1083b70b8e9830b46bf698e85/utils/src/main/kotlin/ProcessCapture.kt#L36)):*
> ```Kotlin
> class ProcessCapture(workingDir: File?, environment: Map<String, String>, vararg command: String) {
>     constructor(vararg command: String) : this(null, *command)
>     constructor(workingDir: File?, vararg command: String) : this(workingDir, mapOf(), *command)
> ```

Nit: Please add a blank line after this one.

---

*[utils/src/main/kotlin/ProcessCapture.kt, line 49 at r1](https://beta.reviewable.io/reviews/heremaps/oss-review-toolkit/442#-L8bfeuy4x_hU3mL34sl:-L8bfeuy4x_hU3mL34sm:b734rnn) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/8363f753f0ad97e1083b70b8e9830b46bf698e85/utils/src/main/kotlin/ProcessCapture.kt#L49)):*
> ```Kotlin
>             .redirectOutput(stdoutFile)
>             .redirectError(stderrFile)
>             .apply {
> ```

You should be able to drop the surrounding `apply`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/heremaps/oss-review-toolkit/442)*

**Comment by sschuberth** [comment]
> analyzer: Implement a package manager for "dep"

I believe this commit message deserves a brief explanation why the new toml dependency is required, and why that implementation is a good choice.

---

Reviewed 4 of 5 files at r4, 1 of 2 files at r5.
Review status: 5 of 18 files reviewed at latest revision, 2 unresolved discussions.

---

*[analyzer/src/main/kotlin/managers/GoDep.kt, line 56 at r4](https://beta.reviewable.io/reviews/heremaps/oss-review-toolkit/442#-L8bhuka8sMnJd5xIF6a:-L8bhuka8sMnJd5xIF6b:b-z8jfkd) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/c6cdc4f6ca979d894f790882fc43aac863c13598/analyzer/src/main/kotlin/managers/GoDep.kt#L56)):*
> ```Kotlin
> 
>         val projects = Toml().read(lockFile).toMap()["projects"] as? List<*> ?: return null
>         val packages: MutableList<Package> = mutableListOf()
> ```

Shorter: val packages = mutableListOf<Package>()

Similar in other places.

---

*[analyzer/src/main/kotlin/managers/GoDep.kt, line 63 at r4](https://beta.reviewable.io/reviews/heremaps/oss-review-toolkit/442#-L8bi7zsEGreqrMKSrDX:-L8bi7zsEGreqrMKSrDY:b72un7s) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/c6cdc4f6ca979d894f790882fc43aac863c13598/analyzer/src/main/kotlin/managers/GoDep.kt#L63)):*
> ```Kotlin
>         for (project in projects) {
>             if (project !is Map<*, *>)
>                 continue  // TODO log warning?
> ```

Nit: If `continue` is on its own line, we require curly braces. So either add curly braces, or move `continue` to the `if` line.

---

*[analyzer/src/main/kotlin/managers/GoDep.kt, line 118 at r4](https://beta.reviewable.io/reviews/heremaps/oss-review-toolkit/442#-L8bibwZBIdDL3EgS6hl:-L8bibwZBIdDL3EgS6hm:b-6asahg) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/c6cdc4f6ca979d894f790882fc43aac863c13598/analyzer/src/main/kotlin/managers/GoDep.kt#L118)):*
> ```Kotlin
> 
>     private fun resolveVcsInfo(vcs: VcsInfo, gopath: File): VcsInfo {
> ```

Nit: Remove blank line.

---

*[analyzer/src/main/kotlin/managers/GoDep.kt, line 23 at r5](https://beta.reviewable.io/reviews/heremaps/oss-review-toolkit/442#-L8bj63BCUkg9C6oekf7:-L8bj63BCUkg9C6oekf8:bx7oss7) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/70b0d2ae5400e44de2ec66c11879b93619fa8cc3/analyzer/src/main/kotlin/managers/GoDep.kt#L23)):*
> ```Kotlin
> 
> import ch.frankel.slf4k.debug
> import ch.frankel.slf4k.warn
> ```

As per our convention this is a wildcard import we allow.

Nit: Add a blank line to separate from imports from different top-level namespace.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/heremaps/oss-review-toolkit/442#-:-L8bhWVJDO33nAHjPPQs:bmx2tjs)*

**Comment by sschuberth** [comment]
Reviewed 7 of 7 files at r6, 5 of 6 files at r7, 1 of 1 files at r8, 5 of 6 files at r9, 1 of 2 files at r10, 1 of 1 files at r11.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks broke.

---

*[.gitmodules, line 21 at r6](https://beta.reviewable.io/reviews/heremaps/oss-review-toolkit/442#-L8bjxXo2MiIl11p7pAQ:-L8bjxXo2MiIl11p7pAR:b7455vi) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/1f013793471f69ba03a412bc1695c90a4573b977/.gitmodules#L21)):*
> ```
> 	url = https://github.com/nexb/scancode-toolkit.git
> 	ignore = untracked
> [submodule "qmstr"]
> ```

How about naming this "Quartermaster" for clarity?

---

*[.gitmodules, line 25 at r7](https://beta.reviewable.io/reviews/heremaps/oss-review-toolkit/442#-L8bkHKw2VCat6RNr4qL:-L8bkHKyEpXfB9NzFvDx:b-ch4wov) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/ac10e0a3d657932d3273d6082bd067371a28953b/.gitmodules#L25)):*
> ```
> 	url = https://github.com/QMSTR/qmstr.git
> 	ignore = untracked
> [submodule "analyzer/src/funTest/assets/projects/external/sprig"]
> ```

Please use a short name here, e.g. "sprig".

---

*[.gitmodules, line 28 at r8](https://beta.reviewable.io/reviews/heremaps/oss-review-toolkit/442#-L8bkgjq3QjZrmdp5AZV:-L8bkgjq3QjZrmdp5AZW:b-vllzrf) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/9ee8dddaa11f6ad2192592dc938dff672884fe5f/.gitmodules#L28)):*
> ```
> 	path = analyzer/src/funTest/assets/projects/external/sprig
> 	url = https://github.com/Masterminds/sprig.git
> 	ignore = untracked
> ```

Squash to commit introducing the submodule.

---

*[analyzer/src/main/kotlin/managers/GoDep.kt, line 29 at r10](https://beta.reviewable.io/reviews/heremaps/oss-review-toolkit/442#-L8blBEc23dDhSG2SKiP:-L8blBEc23dDhSG2SKiQ:b-156qay) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/20ece5f99c18981ab5bb3dc799f6acbb8ff7b240/analyzer/src/main/kotlin/managers/GoDep.kt#L29)):*
> ```Kotlin
> import com.here.ort.downloader.VersionControlSystem
> import com.here.ort.model.AnalyzerResult
> import com.here.ort.model.Identifier
> ```

Squash to commit introducing the wildcard import.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/heremaps/oss-review-toolkit/442)*

**Comment by haikoschol** [comment]
*[analyzer/src/main/kotlin/managers/GoDep.kt, line 56 at r4](https://beta.reviewable.io/reviews/heremaps/oss-review-toolkit/442#-L8bhuka8sMnJd5xIF6a:-L8brqbO0NY2vxAYzHdu:boyjwbs) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/c6cdc4f6ca979d894f790882fc43aac863c13598/analyzer/src/main/kotlin/managers/GoDep.kt#L56)):*
<details><summary><i>Previously, sschuberth (Sebastian Schuberth) wrote…</i></summary><blockquote>

Shorter: val packages = mutableListOf<Package>()

Similar in other places.
</blockquote></details>

"Error:(55, 24) Kotlin: Type inference failed: Not enough information to infer parameter T in inline fun <T> mutableListOf(): MutableList<T>
Please specify it explicitly."

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/heremaps/oss-review-toolkit/442)*

**Comment by haikoschol** [comment]
*[analyzer/src/main/kotlin/managers/GoDep.kt, line 63 at r4](https://beta.reviewable.io/reviews/heremaps/oss-review-toolkit/442#-L8bi7zsEGreqrMKSrDX:-L8brx37BUh7PrnBH2uM:b-1gkejv) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/c6cdc4f6ca979d894f790882fc43aac863c13598/analyzer/src/main/kotlin/managers/GoDep.kt#L63)):*
<details><summary><i>Previously, sschuberth (Sebastian Schuberth) wrote…</i></summary><blockquote>

Nit: If `continue` is on its own line, we require curly braces. So either add curly braces, or move `continue` to the `if` line.
</blockquote></details>

Which `continue` and which `if` are you referring to?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/heremaps/oss-review-toolkit/442)*

**Comment by haikoschol** [comment]
*[.gitmodules, line 21 at r6](https://beta.reviewable.io/reviews/heremaps/oss-review-toolkit/442#-L8bjxXo2MiIl11p7pAQ:-L8bt71PAK7GAR13gNXk:baylicg) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/1f013793471f69ba03a412bc1695c90a4573b977/.gitmodules#L21)):*
<details><summary><i>Previously, sschuberth (Sebastian Schuberth) wrote…</i></summary><blockquote>

How about naming this "Quartermaster" for clarity?
</blockquote></details>

Fine with me, but there are at least two projects written in Go that are actually called "Quartermaster": https://github.com/coreos/quartermaster https://github.com/stevelacy/quartermaster

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/heremaps/oss-review-toolkit/442)*

**Pull request merged**
