### PR TITLE
Improve SVN

### PR DESCRIPTION
**Pull request by sschuberth**
Please have a look at the individual commit messages for the details.

---
This change is [Reviewable](https://reviewable.io/reviews/heremaps/oss-review-toolkit/166)

### CODE REVIEW

**Comment by pnowakowski** [comment]
Review status: 0 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[downloader/src/main/kotlin/vcs/Subversion.kt, line 61 at r5](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/166#-L0mosI382S7MoKo-MZu:-L0mosI382S7MoKo-MZv:bqffbub) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/78a7cb01b945e746c0920c4b33ff85d8ffaa4402/downloader/src/main/kotlin/vcs/Subversion.kt#L61)):*
> ```Kotlin
>                 private val svnInfo = ProcessCapture("svn", "info", workingDir.absolutePath)
>                 private val svnInfoMap = svnInfo.stdout().lines()
>                         .associateBy({ it.substringBefore(": ") }, { it.substringAfter(": ") })
> ```

I don't  like adding single space inside delimiter. It probably isn't common case, but I would use only colon, and then `trim()` to have better chance to parse the output, if it's format is changed. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/166)*

**Comment by sschuberth** [comment]
Review status: 0 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[downloader/src/main/kotlin/vcs/Subversion.kt, line 61 at r5](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/166#-L0mosI382S7MoKo-MZu:-L0n0-1-XUEWSL5yJdT7:bol72xa) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/78a7cb01b945e746c0920c4b33ff85d8ffaa4402/downloader/src/main/kotlin/vcs/Subversion.kt#L61)):*
<details><summary><i>Previously, pnowakowski wrote…</i></summary><blockquote>

I don't  like adding single space inside delimiter. It probably isn't common case, but I would use only colon, and then `trim()` to have better chance to parse the output, if it's format is changed. 
</blockquote></details>

Actually, I was thinking it's even more safe to include that space into the delimiter, so that no single colons in paths, URLs or time stamps are matched. Also, I highly doubt that the output format for `svn info` would change, although I could not find a documented guarantee on it to be stable. If we wanted to be really sure we should use `svn info --xml` anyway, but I don't like the overhead it adds.

@mnonnenmacher, any opinion?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/166)*

**Comment by pnowakowski** [comment]
Review status: 0 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[downloader/src/main/kotlin/vcs/Subversion.kt, line 61 at r5](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/166#-L0mosI382S7MoKo-MZu:-L0n2pt5oMBwKMawDVu6:b-rzqw7) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/78a7cb01b945e746c0920c4b33ff85d8ffaa4402/downloader/src/main/kotlin/vcs/Subversion.kt#L61)):*
<details><summary><i>Previously, sschuberth (Sebastian Schuberth) wrote…</i></summary><blockquote>

Actually, I was thinking it's even more safe to include that space into the delimiter, so that no single colons in paths, URLs or time stamps are matched. Also, I highly doubt that the output format for `svn info` would change, although I could not find a documented guarantee on it to be stable. If we wanted to be really sure we should use `svn info --xml` anyway, but I don't like the overhead it adds.

@mnonnenmacher, any opinion?
</blockquote></details>

I see your point, however `substringBefore(delimileter) ` returns the part before _first_ occurrence of given arg, so additional colon would have to be added in _header_ part of the line, if it is in _value_ part, the division would still happen at the same place.  

However, as you said, it's quite doubtful, the format is changed, it was just my first thought when I saw the line. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/166)*

**Comment by mnonnenmacher** [comment]
Review status: 0 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[downloader/src/main/kotlin/vcs/Subversion.kt, line 61 at r5](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/166#-L0mosI382S7MoKo-MZu:-L0nMl5bq5vVIIx54t4I:b-oe8lla) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/78a7cb01b945e746c0920c4b33ff85d8ffaa4402/downloader/src/main/kotlin/vcs/Subversion.kt#L61)):*
<details><summary><i>Previously, pnowakowski wrote…</i></summary><blockquote>

I see your point, however `substringBefore(delimileter) ` returns the part before _first_ occurrence of given arg, so additional colon would have to be added in _header_ part of the line, if it is in _value_ part, the division would still happen at the same place.  

However, as you said, it's quite doubtful, the format is changed, it was just my first thought when I saw the line. 
</blockquote></details>

Actually I think the XML output is the best way, because that's what it's there for. Also it seems XML output is not localized which makes the implementation independent from locale settings.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/166)*

**Comment by mnonnenmacher** [comment]
Reviewed 4 of 4 files at r1, 11 of 11 files at r2, 5 of 5 files at r3, 1 of 2 files at r4, 2 of 2 files at r6, 2 of 2 files at r7, 1 of 1 files at r8, 4 of 4 files at r9, 1 of 1 files at r10.
Review status: 15 of 17 files reviewed at latest revision, 2 unresolved discussions.

---

*[downloader/src/test/kotlin/SubversionTest.kt, line 57 at r6](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/166#-L0oAge-DhlTOrAZ5HZT:-L0oAge-DhlTOrAZ5HZU:b-gs1hyl) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/6f41c37d5078e05a550492b028b9326ca3b21f45/downloader/src/test/kotlin/SubversionTest.kt#L57)):*
> ```Kotlin
>         spec()
> 
>         zipContentDir.deleteRecursively()
> ```

Do `try { spec() } finally { zipContentDir.deleteRecursively() }` to make sure the directory gets deleted?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/166)*

**Comment by sschuberth** [comment]
Review status: 11 of 17 files reviewed at latest revision, 2 unresolved discussions.

---

*[downloader/src/test/kotlin/SubversionTest.kt, line 57 at r6](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/166#-L0oAge-DhlTOrAZ5HZT:-L0oHUQWIqOoOKyHsfEb:b-896fix) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/6f41c37d5078e05a550492b028b9326ca3b21f45/downloader/src/test/kotlin/SubversionTest.kt#L57)):*
<details><summary><i>Previously, mnonnenmacher (Martin Nonnenmacher) wrote…</i></summary><blockquote>

Do `try { spec() } finally { zipContentDir.deleteRecursively() }` to make sure the directory gets deleted?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/166)*

**Comment by mnonnenmacher** [comment]
Reviewed 6 of 6 files at r11, 2 of 2 files at r12, 1 of 1 files at r13, 4 of 4 files at r14, 1 of 1 files at r15, 2 of 2 files at r16.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/166)*

**Pull request merged**
