### PR TITLE
Matcher cleanups

### PR DESCRIPTION
**Pull request by sschuberth**
Please have a look at the individual commit messages for the details.

### CODE REVIEW

**Comment by fviernau** [comment]
I'm Working on this class currently, it'd be great if we could avoid rebase conflicts. Can you maybe just wait a little with those?

**Comment by sschuberth** [comment]
> Can you maybe just wait a little with those?

Wait with what? I'm already done... and I wasn't really meaning to work on these classes. These things just occurred to me while trying to understand your recent changes.

Or did you mean "wait with merging", not "wait with working on theses classes"?

**Comment by fviernau** [comment]
I meant to ask you whether you would stop changing this class until my refactoring is finished.

**Comment by fviernau** [comment]
IIRC I have communicated before that I m working on this.

**Comment by sschuberth** [comment]
I know you're still working on the larger topic of path-based curations, but I'm having a hard time figuring out which classes exactly will still undergo refactoring in this context. I was assuming these classes would not received bigger changes anymore since you had already refactored them recently. And additionally, my changes are rather minor, so I would not have thought for them to create any real conflicts.

Anyway, please simply ignore this PR then, I'll not merge it and I'll not work on any license / copyright / findings related code until you explicitly confirm you're finished with your refactoring.

**Comment by fviernau** [comment]
Thats appreciated that your willing to defer this merge, anyhow - I'm OK with merging this PR as you have it already done. 

I'd be happy if you could stop crafting additional similar changes conflicting with my refactoring as it creates additional work and also partially at least we're creating the same commits twice.

**Comment by sschuberth** [comment]
> I'm OK with merging this PR as you have it already done.

Thanks. Feel free to approve then if you're ready.

> I'd be happy if you could stop crafting additional similar changes conflicting with my refactoring

Promised! 😅

**Pull request merged**
