### PR TITLE
Unmanaged projects

### PR DESCRIPTION
**Pull request by mnonnenmacher**
Please see the individual commit messages for details.

---
This change is [Reviewable](https://reviewable.io/reviews/heremaps/oss-review-toolkit/371)

### CODE REVIEW

**Comment by sschuberth** [comment]
Reviewed 5 of 5 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[analyzer/src/main/kotlin/Main.kt, line 214 at r3](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/371#-L6X8O5PqEwz9S-hfODx:-L6X8O5PqEwz9S-hfODy:b-e63yc1) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/4a9b18586cc38e4a3054ed69edaeddfd61ecfe1f/analyzer/src/main/kotlin/Main.kt#L214)):*
> ```Kotlin
> 
>         if (managedDefinitionFiles.isEmpty()) {
>             println("No package-managed projects found.")
> ```

Shouldn't this stay as the statement is still true?

---

*[analyzer/src/main/kotlin/managers/Unmanaged.kt, line 44 at r2](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/371#-L6X5rZstUHLDTzADUFx:-L6X5rZtRF5Yj0eYyIly:b-6904xr) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/4ce38892143fbef4357ec449b2bc0c4ff8bc450c/analyzer/src/main/kotlin/managers/Unmanaged.kt#L44)):*
> ```Kotlin
> 
>     override fun resolveDependencies(definitionFile: File): AnalyzerResult? {
>         val vcs = VersionControlSystem.forDirectory(definitionFile)
> ```

How about a code comment here that the `definitionFile` is not actually a file in this case? Or maybe just rename the argument?

---

*[analyzer/src/main/kotlin/managers/Unmanaged.kt, line 56 at r2](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/371#-L6X7MITao3Qv_XtM8oe:-L6X7MIUPGoFg6oIq4aL:b-yvjwua) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/4ce38892143fbef4357ec449b2bc0c4ff8bc450c/analyzer/src/main/kotlin/managers/Unmanaged.kt#L56)):*
> ```Kotlin
>                 aliases = emptyList(),
>                 vcs = VcsInfo.EMPTY,
>                 vcsProcessed = vcs?.getInfo(definitionFile) ?: VcsInfo.EMPTY,
> ```

Doesn't `vcsFromWorkingTree()` (with keeping the second default argument) work here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/371)*

**Comment by mnonnenmacher** [comment]
Review status: 5 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[analyzer/src/main/kotlin/Main.kt, line 214 at r3](https://beta.reviewable.io/reviews/heremaps/oss-review-toolkit/371#-L6X8O5PqEwz9S-hfODx:-L6XvJTLCtPGTaZI05f_:b-9c1m8h) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/4a9b18586cc38e4a3054ed69edaeddfd61ecfe1f/analyzer/src/main/kotlin/Main.kt#L214)):*
<details><summary><i>Previously, sschuberth (Sebastian Schuberth) wrote…</i></summary><blockquote>

Shouldn't this stay as the statement is still true?
</blockquote></details>

I have removed it because it will now print "Unmanaged projects found in..." below instead which seemed sufficient.

---

*[analyzer/src/main/kotlin/managers/Unmanaged.kt, line 44 at r2](https://beta.reviewable.io/reviews/heremaps/oss-review-toolkit/371#-L6X5rZstUHLDTzADUFx:-L6Y3w0SE8i0KDrvRZzy:b-w3tz7y) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/4ce38892143fbef4357ec449b2bc0c4ff8bc450c/analyzer/src/main/kotlin/managers/Unmanaged.kt#L44)):*
<details><summary><i>Previously, sschuberth (Sebastian Schuberth) wrote…</i></summary><blockquote>

How about a code comment here that the `definitionFile` is not actually a file in this case? Or maybe just rename the argument?
</blockquote></details>

Renaming could cause issues with named arguments so I added documentation instead.

---

*[analyzer/src/main/kotlin/managers/Unmanaged.kt, line 56 at r2](https://beta.reviewable.io/reviews/heremaps/oss-review-toolkit/371#-L6X7MITao3Qv_XtM8oe:-L6Y4Zri6Q0IWUv3Ia0R:b-896fix) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/4ce38892143fbef4357ec449b2bc0c4ff8bc450c/analyzer/src/main/kotlin/managers/Unmanaged.kt#L56)):*
<details><summary><i>Previously, sschuberth (Sebastian Schuberth) wrote…</i></summary><blockquote>

Doesn't `vcsFromWorkingTree()` (with keeping the second default argument) work here?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/heremaps/oss-review-toolkit/371)*

**Comment by sschuberth** [comment]
Reviewed 2 of 2 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[analyzer/src/main/kotlin/Main.kt, line 222 at r8](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/371#-L6_ieUyrpHdIfviLLiZ:-L6_ieUyrpHdIfviLLi_:bymo6ud) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/5393d455fa91bd08bed2f51f2e92c4f3217044dc/analyzer/src/main/kotlin/Main.kt#L222)):*
> ```Kotlin
>             println("$manager projects found in:")
>             println(files.joinToString("\n") {
>                 "\t${it.toRelativeString(absoluteProjectPath).let { if (it.isBlank()) "." else it}}"
> ```

Isn't `isEmpty()` sufficient here?

---

*[analyzer/src/main/kotlin/managers/Unmanaged.kt, line 44 at r2](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/371#-L6X5rZstUHLDTzADUFx:-L6_hMcb3UndFPCAkD9Z:bhwnswm) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/4ce38892143fbef4357ec449b2bc0c4ff8bc450c/analyzer/src/main/kotlin/managers/Unmanaged.kt#L44)):*
Ah, I was more thinking about a simple code comment inside the function. Something like

> Note: "definitionFile" is not actually a file but a directory in this context.

Because if we add proper KDoc here, we probably need to add it elsewhere, too ;-)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/371)*

**Comment by sschuberth** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/371#-:-L6_pqtm1MAEeIzZrZaI:bnfp4nl)*

**Pull request merged**
