### PR TITLE
Add external projects for analyzer tests (Robolectric, K9mail, Gradle subprojects: Logging, Wrapper)

### PR DESCRIPTION
**Pull request by pnowakowski**
External Gradle projects added to for testing analyzer results. 

Current analyzer results for external projects added into assets as expected results. Some of them look empty. Those test result with passed result at the moment.

---
This change is [Reviewable](https://reviewable.io/reviews/heremaps/oss-review-toolkit/65)

### CODE REVIEW

**Comment by mnonnenmacher** [comment]
Proposals for commit messages:
r1: "analyzer: Add configuration for integration tests"
r2: "analyzer: Add integration tests for Robolectric"
r5: "analyzer: Add integration tests for K9Mail"

---

Reviewed 1 of 1 files at r1, 1 of 3 files at r2, 1 of 3 files at r3, 2 of 5 files at r4, 1 of 3 files at r5, 1 of 2 files at r6, 2 of 6 files at r7, 8 of 10 files at r8, 25 of 25 files at r9, 12 of 12 files at r10, 1 of 1 files at r11.
Review status: all files reviewed at latest revision, 24 unresolved discussions.

---

*[analyzer/src/funTest/assets/projects/synthetic/gradle-expected-results/gradle/subprojects/wrapper/wrapper-gradle-dependencies.yml, line 16 at r10](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/65#-L-5xr0tmR25yAH-NWU8:-L-5xr0tmR25yAH-NWU9:bxndx1o) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/f9ab72d97857028e44032692ade980006a8321ea/analyzer/src/funTest/assets/projects/synthetic/gradle-expected-results/gradle/subprojects/wrapper/wrapper-gradle-dependencies.yml#L16)):*
> ```YAML
>   homepage_url: ""
>   scopes: []
> packages: []
> ```

Looks suspicious that all the projects don't have any dependencies. Did you check if this is correct?

---

*[analyzer/src/funTest/kotlin/TestTags.kt, line 1 at r8](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/65#-L-1GZAM4Cj9ZsjL0AwG:-L-1GZAM4Cj9ZsjL0AwH:bepup3c) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/d53c9f79b641ac7b74bf9e25c97c688e4e3405b5/analyzer/src/funTest/kotlin/TestTags.kt#L1)):*
> ```Kotlin
> package com.here.ort.analyzer
> ```

Do this in the first commit instead, and update the commit message.

---

*[analyzer/src/funTest/kotlin/gradle/BaseGradleSpec.kt, line 35 at r9](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/65#-L-5x-LLcCNYxoZWDHo9:-L-5x-LLcCNYxoZWDHoA:b-twl7nh) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/1765db12e2903f4854fd8c4ad5caa6791d01ad2c/analyzer/src/funTest/kotlin/gradle/BaseGradleSpec.kt#L35)):*
> ```Kotlin
> 
>     init {
>         "analyzer produces ABCD files for all pkg .gradle files" {
> ```

Remove 'pkg'.

---

*[analyzer/src/funTest/kotlin/gradle/BaseGradleSpec.kt, line 44 at r9](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/65#-L-5wNA2rE6LPZ6vQzH8:-L-5wNA2rE6LPZ6vQzH9:btq97o8) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/1765db12e2903f4854fd8c4ad5caa6791d01ad2c/analyzer/src/funTest/kotlin/gradle/BaseGradleSpec.kt#L44)):*
> ```Kotlin
>             ))
> 
>             val sourceGradleProjectFiles = downloadedDir.walkTopDown().asIterable().filter { file: File ->
> ```

`asIterable()`is not required, you can apply `filter()`directly.

---

*[analyzer/src/funTest/kotlin/gradle/BaseGradleSpec.kt, line 51 at r9](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/65#-L-5wAPpwa2jcKSHj4jf:-L-5wAPq5fVHRAbNIVXv:b82ecao) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/1765db12e2903f4854fd8c4ad5caa6791d01ad2c/analyzer/src/funTest/kotlin/gradle/BaseGradleSpec.kt#L51)):*
> ```Kotlin
> 
>             val expectedResult = sourceGradleProjectFiles.map {
>                 val abcdFileDir = it.absolutePath.substringBeforeLast(File.separator).replace(oldValue = downloadedDir.absolutePath, newValue = analyzerResultsDir.absolutePath, ignoreCase = true)
> ```

We have a line length limit of 120, please add line breaks where it applies.

---

*[analyzer/src/funTest/kotlin/gradle/BaseGradleSpec.kt, line 54 at r9](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/65#-L-5wjl9lhsCXVRvEMXA:-L-5wjl9lhsCXVRvEMXB:btq97o8) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/1765db12e2903f4854fd8c4ad5caa6791d01ad2c/analyzer/src/funTest/kotlin/gradle/BaseGradleSpec.kt#L54)):*
> ```Kotlin
>                 abcdFileDir + File.separator + "build-gradle-dependencies.yml"
>             }.toSet()
>             val generatedResultFiles = analyzerResultsDir.walkTopDown().asIterable().filter { it.extension == "yml" }.map{it.absolutePath}.toSet()
> ```

`asIterable()`is not required, you can apply `filter()`directly.

---

*[analyzer/build.gradle, line 1 at r8](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/65#-L-1GOrUEroBF1Ra2IpL:-L-1GOrUEroBF1Ra2IpM:b-lnf2xz) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/d53c9f79b641ac7b74bf9e25c97c688e4e3405b5/analyzer/build.gradle#L1)):*
> ```Gradle
> // Apply core plugins.
> ```

Do this in the first commit instead, and update the commit message accordingly.

---

*[analyzer/src/funTest/kotlin/integration/BaseIntegrationSpec.kt, line 51 at r8](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/65#-L-1GcCyDqTUI4NM8qYx:-L-1GcCyDqTUI4NM8qYy:b-h6yt49) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/d53c9f79b641ac7b74bf9e25c97c688e4e3405b5/analyzer/src/funTest/kotlin/integration/BaseIntegrationSpec.kt#L51)):*
> ```Kotlin
>             generatedResultFiles shouldBe expectedResult
> 
>         }.config(tags = setOf(Expensive))
> ```

Add the tags in the commits where you introduce the tests instead, same for the tags below.

---

*[analyzer/src/intTest/kotlin/BaseIntegrationSpec.kt, line 16 at r4](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/65#-L-1AhCogXTIAw4JVSrO:-L-1AhCpOcnEzcdbXDNz:b-xoqg4a) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/3c4cc2b8aa2d08ac42fc1a0e9e72fa2874f72ee9/analyzer/src/intTest/kotlin/BaseIntegrationSpec.kt#L16)):*
> ```Kotlin
> abstract class BaseIntegrationSpec : StringSpec() {
> 
>     abstract val pkg : Package
> ```

No space after "pkg"? Please always use the IntelliJ formatter with default settings for Kotlin to ensure we have consistent formatting in the project.

---

*[analyzer/src/intTest/kotlin/BaseIntegrationSpec.kt, line 17 at r4](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/65#-L-1B6F8xlpGk281MwRs:-L-1B6F9UV6lHpWt_ojW:bw1r7ct) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/3c4cc2b8aa2d08ac42fc1a0e9e72fa2874f72ee9/analyzer/src/intTest/kotlin/BaseIntegrationSpec.kt#L17)):*
> ```Kotlin
> 
>     abstract val pkg : Package
>     private val outputDir = createTempDir()
> ```

Shouldn't "createTempDir" happen in interceptSpec below, to ensure that there is a new temp dir for each test? Otherwise only the first test will work. Could be `private lateinit var outputDir: File`then.

---

*[analyzer/src/intTest/kotlin/BaseIntegrationSpec.kt, line 25 at r4](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/65#-L-1BeouiPSKLMhMAYtR:-L-1Beov0Uzl5B9Q_IsD:bfo5ov4) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/3c4cc2b8aa2d08ac42fc1a0e9e72fa2874f72ee9/analyzer/src/intTest/kotlin/BaseIntegrationSpec.kt#L25)):*
> ```Kotlin
> 
>     init {
>         "analyzer produces ABCD files for all pkg build.gradle files" {
> ```

This is Gradle specific, mabye the class should be called BaseGradleIntegrationSpec or you could move the test to a derived class with this name.

---

*[analyzer/src/intTest/kotlin/BaseIntegrationSpec.kt, line 26 at r4](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/65#-L-1CKY_IAOnH6fNLgI2:-L-1CKY_IAOnH6fNLgI3:b-v6ryau) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/3c4cc2b8aa2d08ac42fc1a0e9e72fa2874f72ee9/analyzer/src/intTest/kotlin/BaseIntegrationSpec.kt#L26)):*
> ```Kotlin
>     init {
>         "analyzer produces ABCD files for all pkg build.gradle files" {
>             //FIXME:  Analyzer crashes on JAVA 9 with project below Gradle 4.3 (Gradle issue: https://github.com/gradle/gradle/issues/3317)
> ```

Interesting.
In the link they mention version 4.2.1 instead of 4.3.

---

*[analyzer/src/intTest/kotlin/BaseIntegrationSpec.kt, line 48 at r6](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/65#-L-1EJS6Ze0-5MPA0bn5:-L-1EJS6Ze0-5MPA0bn6:b-ig9p7w) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/e6bb9a59ff2a13f88564e0f9bdce60d3f746f748/analyzer/src/intTest/kotlin/BaseIntegrationSpec.kt#L48)):*
> ```Kotlin
>             }.toSet()
>             val generatedResultFiles = analyzerResultsDir.walkTopDown().asIterable().filter { it.extension == "yml" }.map{it.absolutePath}.toSet()
>             generatedResultFiles shouldBe expectedResult
> ```

Looks like this code should be in the function below.

---

*[analyzer/src/intTest/kotlin/BaseIntegrationSpec.kt, line 53 at r6](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/65#-L-1EQax1zusfUTCVerZ:-L-1EQax1zusfUTCVer_:b-cdnjk5) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/e6bb9a59ff2a13f88564e0f9bdce60d3f746f748/analyzer/src/intTest/kotlin/BaseIntegrationSpec.kt#L53)):*
> ```Kotlin
> 
>         "analyzer results match expected ABCD files" {
>             //TODO: add expected ABCD files to assets and test if all produced analyzer outputs match corresponding expected files
> ```

Tests and required assets should be added in the same commit. The general rule is: Every single commit needs to pass all tests. This is important e.g. when you use `git bisect`.

Unfortunately we cannot automatically verify this on GitHub. On gerrit tests are run for each commit, not only for the last one.

---

*[analyzer/src/intTest/kotlin/K9MailTest.kt, line 21 at r5](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/65#-L-1DGmv-Xn2EJBO7FWY:-L-1DGmwKAOHIer0Q_8j:bl03rww) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/6ac52d9659651c8586de09579d49120fcb80f865/analyzer/src/intTest/kotlin/K9MailTest.kt#L21)):*
> ```Kotlin
>             hashAlgorithm = "",
>             hash = "",
>             vcsRevision = "")
> ```

Please add a vcsRevision so that we don't depend on a changing version of K9Mail.

---

*[analyzer/src/intTest/kotlin/K9MailTest.kt, line 21 at r7](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/65#-L-1FScjYw2Q_JmDj2bN:-L-1FScjYw2Q_JmDj2bO:b-rz24y4) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/7d97109e875797ad22496f49682c6a70d5a77f59/analyzer/src/intTest/kotlin/K9MailTest.kt#L21)):*
> ```Kotlin
>             hashAlgorithm = "",
>             hash = "",
>             //TODO: add a revision to have stable analyzer results
> ```

So do it in the original commit :)

---

*[analyzer/src/intTest/kotlin/RobolectricTest.kt, line 9 at r2](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/65#-L-18yhZGf15mAblM9nK:-L-18yh_grpbp5kMHYtD:bi3xwls) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/65a157e1ef3daf4ce7f66f0e992de63a8bd8c626/analyzer/src/intTest/kotlin/RobolectricTest.kt#L9)):*
> ```Kotlin
> import java.io.File
> import com.here.ort.downloader.Main as DownloaderMain
> import com.here.ort.analyzer.Main as AnalyzerMain
> ```

It's nit-picking, but we care for the formatting of imports: alphabetic order, group by top-level-domain with empty lines in between. Just check the other source files for examples. In this case:

```
com.here...

io.kotlintest...

java.io...
```

Please also check this in all follow-up commits.

---

*[analyzer/src/intTest/kotlin/RobolectricTest.kt, line 17 at r2](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/65#-L-15Av71wV07ZnuuCFC:-L-15Av71wV07ZnuuCFD:bu330y4) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/65a157e1ef3daf4ce7f66f0e992de63a8bd8c626/analyzer/src/intTest/kotlin/RobolectricTest.kt#L17)):*
> ```Kotlin
>     fun after() {
>         outputDir.deleteRecursively()
>     }
> ```

Does this work with kotlintest? I thought you have to use an interceptor:
https://github.com/kotlintest/kotlintest/blob/master/doc/reference.md#interceptors-

---

*[analyzer/src/intTest/kotlin/RobolectricTest.kt, line 33 at r2](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/65#-L-160zGj4kAaOQJswBZ:-L-160zGj4kAaOQJswB_:b-pov3i5) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/65a157e1ef3daf4ce7f66f0e992de63a8bd8c626/analyzer/src/intTest/kotlin/RobolectricTest.kt#L33)):*
> ```Kotlin
>             hashAlgorithm = "",
>             hash = "",
>             vcsRevision = "")
> ```

Please put the arguments in the same order as in other places for consistency, for example:

```
Package(
                            packageManager = javaClass.simpleName,
                            namespace = project.groupId,
                            name = project.artifactId,
                            version = project.version,
                            declaredLicenses = maven.parseLicenses(project),
                            description = project.description ?: "",
                            homepageUrl = project.url ?: "",
                            downloadUrl = "", // TODO: Try to get URL for downloaded dependencies.
                            hash = "", // TODO: Get hash from local metadata?
                            hashAlgorithm = "",
                            vcsProvider = maven.parseVcsProvider(project),
                            vcsUrl = maven.parseVcsUrl(project),
                            vcsRevision = maven.parseVcsRevision(project),
                            vcsPath = ""
                    )
```

Also, did you verify that the downloader is using the correct tag for the download? Just to make sure we depend on a fixed revision.

---

*[analyzer/src/intTest/kotlin/RobolectricTest.kt, line 37 at r2](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/65#-L-17JNmBb5kxC3T8tiM:-L-17JNmBb5kxC3T8tiN:bxajs3v) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/65a157e1ef3daf4ce7f66f0e992de63a8bd8c626/analyzer/src/intTest/kotlin/RobolectricTest.kt#L37)):*
> ```Kotlin
>     init {
>         "analyzer produces ABCD files for all robolectric build.gradle files" {
>             val downloadedDir = DownloaderMain.download(robolectricPackage, outputDir)
> ```

"downloadDir" sounds better to me.

---

*[analyzer/src/intTest/kotlin/RobolectricTest.kt, line 44 at r2](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/65#-L-17gKSdZUokubdWDIA:-L-17gKSdZUokubdWDIB:b-uhnfq8) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/65a157e1ef3daf4ce7f66f0e992de63a8bd8c626/analyzer/src/intTest/kotlin/RobolectricTest.kt#L44)):*
> ```Kotlin
>             ))
> 
>             val sourceGradleProjectFiles = downloadedDir.walkTopDown().asIterable().filter { file: File ->
> ```

I think you don't need "asIterable()", you can apply filter() directly to walkTopDown().

---

*[analyzer/src/intTest/kotlin/RobolectricTest.kt, line 50 at r2](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/65#-L-181-xjhfcWIMN5zVS:-L-181-xjhfcWIMN5zVT:bd20eg5) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/65a157e1ef3daf4ce7f66f0e992de63a8bd8c626/analyzer/src/intTest/kotlin/RobolectricTest.kt#L50)):*
> ```Kotlin
>             }
> 
>             analyzerResultsDir.walkTopDown().asIterable().filter { it.extension == "yml" }.count() shouldBe sourceGradleProjectFiles.size
> ```

Same as above.
Also since all build files are called "build.gradle" it should be `filter { it.name == "build-gradle-dependencies.yml" }`. There are two other yml files in the Robolectric repo: "circle.yml" and ".travis.yml".

---

*[analyzer/src/intTest/kotlin/RobolectricTest.kt, line 22 at r3](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/65#-L-18fYjJZcm1k_O816D:-L-18fYkQoeBSKITo5-K:b-x1s490) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/08d2c4169c4272eead6cd4140e800651c9b8660c/analyzer/src/intTest/kotlin/RobolectricTest.kt#L22)):*
> ```Kotlin
>         spec();
>         outputDir.deleteRecursively()
>     }
> ```

This should be squashed into the previous commit. No need to have fixup commits before your PR is merged, just fix it in the original commit right away.

---

*[analyzer/src/intTest/kotlin/RobolectricTest.kt, line 29 at r7](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/65#-L-1FWRLGCo0m3ny7sU3:-L-1FWRLGCo0m3ny7sU4:b-gzkgb8) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/7d97109e875797ad22496f49682c6a70d5a77f59/analyzer/src/intTest/kotlin/RobolectricTest.kt#L29)):*
> ```Kotlin
>             hashAlgorithm = "",
>             hash = "",
>             //TODO: add a revision to have stable analyzer results
> ```

Not wrong, but shouldn't be necessary as the downloader should be smart enough to find the correct tag based on the version. Again, this should happen in the original commit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/65#-:-L-14WWvSoPwB3zDeFoE:b-vxgris)*

**Comment by pnowakowski** [comment]
Review status: 12 of 34 files reviewed at latest revision, 24 unresolved discussions, some commit checks failed.

---

*[analyzer/src/funTest/assets/projects/synthetic/gradle-expected-results/gradle/subprojects/wrapper/wrapper-gradle-dependencies.yml, line 16 at r10](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/65#-L-5xr0tmR25yAH-NWU8:-L-62993gh5y_1o2aXP2:bqxedks) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/f9ab72d97857028e44032692ade980006a8321ea/analyzer/src/funTest/assets/projects/synthetic/gradle-expected-results/gradle/subprojects/wrapper/wrapper-gradle-dependencies.yml#L16)):*
<details><summary><i>Previously, mnonnenmacher (Martin Nonnenmacher) wrote…</i></summary><blockquote>

Looks suspicious that all the projects don't have any dependencies. Did you check if this is correct?
</blockquote></details>

As I described in PR: "Current analyzer results for external projects added into assets as expected results. Some of them look empty. Those test result with passed result at the moment."

I wasn't sure what's best approach. Looks like analyzer cannot produce better output, that could be stored as expected result. 
Maybe for now, checking expected results can be skipped (it's obviously invalid anyway) and test could check if any dependencies are present in analyzer result produced during test. This way test would fail at the moment. 

---

*[analyzer/src/funTest/kotlin/TestTags.kt, line 1 at r8](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/65#-L-1GZAM4Cj9ZsjL0AwG:-L-68B9tdWVbG8qSeYbx:bb6un1j) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/d53c9f79b641ac7b74bf9e25c97c688e4e3405b5/analyzer/src/funTest/kotlin/TestTags.kt#L1)):*
<details><summary><i>Previously, mnonnenmacher (Martin Nonnenmacher) wrote…</i></summary><blockquote>

Do this in the first commit instead, and update the commit message.
</blockquote></details>

Done

---

*[analyzer/src/funTest/kotlin/gradle/BaseGradleSpec.kt, line 35 at r9](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/65#-L-5x-LLcCNYxoZWDHo9:-L-6DQf99I0-oQbM7yld:b-896fix) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/1765db12e2903f4854fd8c4ad5caa6791d01ad2c/analyzer/src/funTest/kotlin/gradle/BaseGradleSpec.kt#L35)):*
<details><summary><i>Previously, mnonnenmacher (Martin Nonnenmacher) wrote…</i></summary><blockquote>

Remove 'pkg'.
</blockquote></details>

Done.

---

*[analyzer/src/funTest/kotlin/gradle/BaseGradleSpec.kt, line 44 at r9](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/65#-L-5wNA2rE6LPZ6vQzH8:-L-6DQ4S6LuXZPoWUCj2:b-896fix) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/1765db12e2903f4854fd8c4ad5caa6791d01ad2c/analyzer/src/funTest/kotlin/gradle/BaseGradleSpec.kt#L44)):*
<details><summary><i>Previously, mnonnenmacher (Martin Nonnenmacher) wrote…</i></summary><blockquote>

`asIterable()`is not required, you can apply `filter()`directly.
</blockquote></details>

Done.

---

*[analyzer/src/funTest/kotlin/gradle/BaseGradleSpec.kt, line 51 at r9](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/65#-L-5wAPpwa2jcKSHj4jf:-L-6DUStY_qk1ZyEkejm:b-896fix) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/1765db12e2903f4854fd8c4ad5caa6791d01ad2c/analyzer/src/funTest/kotlin/gradle/BaseGradleSpec.kt#L51)):*
<details><summary><i>Previously, mnonnenmacher (Martin Nonnenmacher) wrote…</i></summary><blockquote>

We have a line length limit of 120, please add line breaks where it applies.
</blockquote></details>

Done.

---

*[analyzer/src/funTest/kotlin/gradle/BaseGradleSpec.kt, line 54 at r9](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/65#-L-5wjl9lhsCXVRvEMXA:-L-6DV3K4OoqTgnjj27D:b-896fix) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/1765db12e2903f4854fd8c4ad5caa6791d01ad2c/analyzer/src/funTest/kotlin/gradle/BaseGradleSpec.kt#L54)):*
<details><summary><i>Previously, mnonnenmacher (Martin Nonnenmacher) wrote…</i></summary><blockquote>

`asIterable()`is not required, you can apply `filter()`directly.
</blockquote></details>

Done.

---

*[analyzer/src/funTest/kotlin/gradle/K9MailTest.kt, line 21 at r5](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/65#-L-1DGmv-Xn2EJBO7FWY:-L-6JP_EIQar_bW-Xsnh:b-896fix) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/6ac52d9659651c8586de09579d49120fcb80f865/analyzer/src/funTest/kotlin/gradle/K9MailTest.kt#L21)):*
<details><summary><i>Previously, mnonnenmacher (Martin Nonnenmacher) wrote…</i></summary><blockquote>

Please add a vcsRevision so that we don't depend on a changing version of K9Mail.
</blockquote></details>

Done.

---

*[analyzer/src/funTest/kotlin/gradle/K9MailTest.kt, line 21 at r7](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/65#-L-1FScjYw2Q_JmDj2bN:-L-6JP4qTHomck9R7zYB:b-896fix) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/7d97109e875797ad22496f49682c6a70d5a77f59/analyzer/src/funTest/kotlin/gradle/K9MailTest.kt#L21)):*
<details><summary><i>Previously, mnonnenmacher (Martin Nonnenmacher) wrote…</i></summary><blockquote>

So do it in the original commit :)
</blockquote></details>

Done.

---

*[analyzer/src/funTest/kotlin/gradle/RobolectricTest.kt, line 33 at r2](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/65#-L-160zGj4kAaOQJswBZ:-L-6KHunHQgzuVXaKupi:b-896fix) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/65a157e1ef3daf4ce7f66f0e992de63a8bd8c626/analyzer/src/funTest/kotlin/gradle/RobolectricTest.kt#L33)):*
<details><summary><i>Previously, mnonnenmacher (Martin Nonnenmacher) wrote…</i></summary><blockquote>

Please put the arguments in the same order as in other places for consistency, for example:

```
Package(
                            packageManager = javaClass.simpleName,
                            namespace = project.groupId,
                            name = project.artifactId,
                            version = project.version,
                            declaredLicenses = maven.parseLicenses(project),
                            description = project.description ?: "",
                            homepageUrl = project.url ?: "",
                            downloadUrl = "", // TODO: Try to get URL for downloaded dependencies.
                            hash = "", // TODO: Get hash from local metadata?
                            hashAlgorithm = "",
                            vcsProvider = maven.parseVcsProvider(project),
                            vcsUrl = maven.parseVcsUrl(project),
                            vcsRevision = maven.parseVcsRevision(project),
                            vcsPath = ""
                    )
```

Also, did you verify that the downloader is using the correct tag for the download? Just to make sure we depend on a fixed revision.
</blockquote></details>

Done.

---

*[analyzer/src/funTest/kotlin/gradle/RobolectricTest.kt, line 44 at r2](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/65#-L-17gKSdZUokubdWDIA:-L-6MJVba1bCNZaspAi4:b-896fix) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/65a157e1ef3daf4ce7f66f0e992de63a8bd8c626/analyzer/src/funTest/kotlin/gradle/RobolectricTest.kt#L44)):*
<details><summary><i>Previously, mnonnenmacher (Martin Nonnenmacher) wrote…</i></summary><blockquote>

I think you don't need "asIterable()", you can apply filter() directly to walkTopDown().
</blockquote></details>

Done.

---

*[analyzer/src/funTest/kotlin/gradle/RobolectricTest.kt, line 50 at r2](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/65#-L-181-xjhfcWIMN5zVS:-L-6MKNe-IxWaO7Y5pwT:b-896fix) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/65a157e1ef3daf4ce7f66f0e992de63a8bd8c626/analyzer/src/funTest/kotlin/gradle/RobolectricTest.kt#L50)):*
<details><summary><i>Previously, mnonnenmacher (Martin Nonnenmacher) wrote…</i></summary><blockquote>

Same as above.
Also since all build files are called "build.gradle" it should be `filter { it.name == "build-gradle-dependencies.yml" }`. There are two other yml files in the Robolectric repo: "circle.yml" and ".travis.yml".
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/65)*

**Comment by mnonnenmacher** [comment]
Reviewed 2 of 10 files at r8, 2 of 25 files at r9, 22 of 22 files at r12.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[analyzer/src/funTest/assets/projects/synthetic/gradle-expected-results/gradle/subprojects/wrapper/wrapper-gradle-dependencies.yml, line 16 at r10](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/65#-L-5xr0tmR25yAH-NWU8:-L-6QhygRaV2MbtjZqFy:b-pmroo6) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/f9ab72d97857028e44032692ade980006a8321ea/analyzer/src/funTest/assets/projects/synthetic/gradle-expected-results/gradle/subprojects/wrapper/wrapper-gradle-dependencies.yml#L16)):*
<details><summary><i>Previously, pnowakowski wrote…</i></summary><blockquote>

As I described in PR: "Current analyzer results for external projects added into assets as expected results. Some of them look empty. Those test result with passed result at the moment."

I wasn't sure what's best approach. Looks like analyzer cannot produce better output, that could be stored as expected result. 
Maybe for now, checking expected results can be skipped (it's obviously invalid anyway) and test could check if any dependencies are present in analyzer result produced during test. This way test would fail at the moment. 
</blockquote></details>

Agreed to keep it as is, I will have a look after the merge.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/65)*

**Comment by mnonnenmacher** [comment]
Reviewed 2 of 10 files at r8, 2 of 25 files at r9, 5 of 5 files at r13.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/65)*

**Pull request merged**
