### PR TITLE
Gradle: Enable the build scan plugin for (non-scheduled) CI builds

### PR DESCRIPTION
**Pull request by sschuberth**
See https://guides.gradle.org/creating-build-scans/.

Signed-off-by: Sebastian Schuberth <sebastian.schuberth@here.com>

---
This change is [Reviewable](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1325)

### CODE REVIEW

**Comment by tsteenbe** [comment]
Can we add a Gradle task `buildScan`? 

I know from https://guides.gradle.org/creating-build-scans/ you can run a  `./gradlew build --scan` but I always forget the many configuration options so I would welcome a Gradle task for this that's documented in our README.

**Comment by sschuberth** [comment]
How can you better remember `buildScan` than `build --scan`?

**Comment by sschuberth** [comment]
The build scan for this PR is available at https://gradle.com/s/hueigpqer5pzk as an example.

**Comment by tsteenbe** [comment]
> How can you better remember `buildScan` than `build --scan`?

I would not have to remember either I could simply look up the task in the table at the bottom in README or run `gradle tasks` ;-)

**Comment by sschuberth** [comment]
I don't really think we need such a wrapper task. `build --scan` is usually nothing you'd regularly execute locally, it's more a build debugging / profiling tool. On CI it makes sense to execute regularly to get a build time trend, similar to Jenkins.

**Pull request merged**
