### PR TITLE
Add SBT support via "sbt makePom"

### PR DESCRIPTION
**Pull request by sschuberth**
Please have a look at the individual commit messages for the details.

---
This change is [Reviewable](https://reviewable.io/reviews/heremaps/oss-review-toolkit/55)

### CODE REVIEW

**Comment by mnonnenmacher** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 4 of 4 files at r3, 7 of 7 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[appveyor.yml, line 17 at r4](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/55#-KzdP2aswF9kqokL_tcr:-KzdP2aswF9kqokL_tcs:b1gmocs) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/a6669d8166b45e761176c2aafd1bd88560265007/appveyor.yml#L17)):*
> ```YAML
>   - npm install -g npm@5.5.1 yarn@1.3.2
>   - pip install virtualenv==15.1.0
>   - choco install sbt --version 1.0.2
> ```

Appveyor uses chocolatey, interesting.

---

*[analyzer/src/funTest/kotlin/SbtTest.kt, line 52 at r4](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/55#-KzdPjpBHzNqRqHa39di:-KzdPjpCgpKqvRvo8jg8:b151a76) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/a6669d8166b45e761176c2aafd1bd88560265007/analyzer/src/funTest/kotlin/SbtTest.kt#L52)):*
> ```Kotlin
>             val expectedResult = expectedOutputFile.readText()
> 
>             actualResult shouldBe expectedResult
> ```

Not a must have for me, but I like the readability of the AAA pattern in unit tests as we have it in at least most other tests.

---

*[analyzer/src/main/kotlin/managers/SBT.kt, line 100 at r4](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/55#-KzdQH1f-Ufqz7YV0WyT:-KzdQH1f-Ufqz7YV0WyU:b-17lr9g) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/a6669d8166b45e761176c2aafd1bd88560265007/analyzer/src/main/kotlin/managers/SBT.kt#L100)):*
> ```Kotlin
>     }
> 
>     override fun resolveDependencies(projectDir: File, definitionFiles: List<File>) =
> ```

Instead of opening this function, couldn't you instead forward to Maven in the other resolveDependencies function?

---

*[util/src/main/kotlin/ProcessCapture.kt, line 116 at r1](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/55#-KzdM-h3pBPP9dKGsNtk:-KzdM-h4kHJJPVbC-xy4:b-pwuph) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/58c05f310633143c83dec7091802e9ffdda8f4ce/util/src/main/kotlin/ProcessCapture.kt#L116)):*
> ```Kotlin
>     val actualVersion = getCommandVersion(command, versionArgument, version.type, transform)
>     if (!criterion(actualVersion, version)) {
>         val message = "Unsupported $command version $actualVersion."
> ```

This doesn't tell me anymore what version is required. If I saw it correctly we currently only need it for the SBT check the check actualVersion >= expectedVersion. Maybe we could use semver version ranges for that together with satisfies(...):
https://github.com/vdurmont/semver4j#requirements

And then print the version expression in the error message.

---

*[util/src/main/kotlin/ProcessCapture.kt, line 134 at r2](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/55#-KzdO7lRC8l0cbd9MI82:-KzdO7lRC8l0cbd9MI83:b516rio) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/6f4408d0f5a63ff5a37dedff029071095e5c919d/util/src/main/kotlin/ProcessCapture.kt#L134)):*
> ```Kotlin
>         workingDir: File? = null,
>         transform: (String) -> String = { it },
>         semverType: Semver.SemverType = Semver.SemverType.LOOSE
> ```

Why switch the order of transfrom and semverType? If the function type is the last argument you can also use the nice syntax like `getCommandVersion(...) {}`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/55)*

**Comment by sschuberth** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[analyzer/src/funTest/kotlin/SbtTest.kt, line 52 at r4](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/55#-KzdPjpBHzNqRqHa39di:-KzdSXQnZ7l3wVya84Xu:bpmortw) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/a6669d8166b45e761176c2aafd1bd88560265007/analyzer/src/funTest/kotlin/SbtTest.kt#L52)):*
<details><summary><i>Previously, mnonnenmacher (Martin Nonnenmacher) wrote…</i></summary><blockquote>

Not a must have for me, but I like the readability of the AAA pattern in unit tests as we have it in at least most other tests.
</blockquote></details>

I've added comments why this doesn't work so well in this case.

---

*[util/src/main/kotlin/ProcessCapture.kt, line 134 at r2](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/55#-KzdO7lRC8l0cbd9MI82:-KzdTBr-iv5Rr_7Tbfeo:b-n4ofj8) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/6f4408d0f5a63ff5a37dedff029071095e5c919d/util/src/main/kotlin/ProcessCapture.kt#L134)):*
<details><summary><i>Previously, mnonnenmacher (Martin Nonnenmacher) wrote…</i></summary><blockquote>

Why switch the order of transfrom and semverType? If the function type is the last argument you can also use the nice syntax like `getCommandVersion(...) {}`.
</blockquote></details>

Good point. I wanted to have variables roughly in the order they are used, but I'll revert that bit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/55)*

**Comment by sschuberth** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[util/src/main/kotlin/ProcessCapture.kt, line 116 at r1](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/55#-KzdM-h3pBPP9dKGsNtk:-KzddkKuHyfyxYabb48g:b-896fix) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/58c05f310633143c83dec7091802e9ffdda8f4ce/util/src/main/kotlin/ProcessCapture.kt#L116)):*
<details><summary><i>Previously, mnonnenmacher (Martin Nonnenmacher) wrote…</i></summary><blockquote>

This doesn't tell me anymore what version is required. If I saw it correctly we currently only need it for the SBT check the check actualVersion >= expectedVersion. Maybe we could use semver version ranges for that together with satisfies(...):
https://github.com/vdurmont/semver4j#requirements

And then print the version expression in the error message.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/55)*

**Comment by sschuberth** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[analyzer/src/main/kotlin/managers/SBT.kt, line 100 at r4](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/55#-KzdQH1f-Ufqz7YV0WyT:-KzdeXFUiTe5-BFCJDGH:b34ivvn) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/a6669d8166b45e761176c2aafd1bd88560265007/analyzer/src/main/kotlin/managers/SBT.kt#L100)):*
<details><summary><i>Previously, mnonnenmacher (Martin Nonnenmacher) wrote…</i></summary><blockquote>

Instead of opening this function, couldn't you instead forward to Maven in the other resolveDependencies function?
</blockquote></details>

There would be basically two problems: 1) I already have multiple POM files but the other `resolveDependencies()` function takes only a single `definitionFile`, and 2) Maven's `prepareResolution()` would not get called.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/55)*

**Comment by mnonnenmacher** [comment]
Reviewed 1 of 11 files at r6, 1 of 1 files at r7, 3 of 4 files at r8, 8 of 8 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/55)*

**Comment by mnonnenmacher** [comment]
Reviewed 1 of 1 files at r11, 3 of 4 files at r12, 8 of 8 files at r13.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/55)*

**Pull request merged**
