### PR TITLE
Gradle remote artifacts

### PR DESCRIPTION
**Pull request by mnonnenmacher**
See the individual commit messages for details.

---
This change is [Reviewable](https://reviewable.io/reviews/heremaps/oss-review-toolkit/102)

### CODE REVIEW

**Comment by sschuberth** [comment]
> 780c932

This commit message now needs the body text removed (see previous commit).

---

Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
Review status: 2 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/102#-:-L-aZlEsC2aNNSLFqnSX:b-30trc2)*

**Comment by mnonnenmacher** [comment]
Done.

---

Review status: 2 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/102#-:-L-aafjNUeuw_wWx8KHv:b-896fix)*

**Comment by sschuberth** [comment]
Reviewed 5 of 5 files at r3.
Review status: 4 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[analyzer/src/funTest/kotlin/GradleTest.kt, line 61 at r3](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/102#-L-a_OW_I6ygSUiFsCB3:-L-a_OWa2aNC670NXCcQ:b-k0de7q) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/780c9326905f9bb9b2ff4e3ecf6eb984e8d17586/analyzer/src/funTest/kotlin/GradleTest.kt#L61)):*
> ```Kotlin
> 
>             result shouldNotBe null
>             result!!.errors.joinToString("\n") shouldBe emptyList<String>().joinToString("\n")
> ```

Can't we just use `should beEmpty()` on `errors` here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/102)*

**Comment by sschuberth** [comment]
Reviewed 3 of 3 files at r5, 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[analyzer/src/main/kotlin/managers/Gradle.kt, line 113 at r6](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/102#-L-abDbw96uQoJCQ8ROe:-L-abDbw96uQoJCQ8ROf:buahy5j) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/48b468314bb3bd4e2b70543bce730eccef39f9e2/analyzer/src/main/kotlin/managers/Gradle.kt#L113)):*
> ```Kotlin
>             }
> 
>             log.debug { "Using Maven repositories from Gradle project: $repositories" }
> ```

Should this say "for Gradle project"? Also, this sounds as if you were listing Gradle projects. maybe invert the sentence and say something like "This Gradle project uses the following Maven repositories"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/102)*

**Comment by mnonnenmacher** [comment]
Review status: 3 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[analyzer/src/funTest/kotlin/GradleTest.kt, line 61 at r3](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/102#-L-a_OW_I6ygSUiFsCB3:-L-ag-XUB381TSyxnJrT:b-896fix) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/780c9326905f9bb9b2ff4e3ecf6eb984e8d17586/analyzer/src/funTest/kotlin/GradleTest.kt#L61)):*
<details><summary><i>Previously, sschuberth (Sebastian Schuberth) wrote…</i></summary><blockquote>

Can't we just use `should beEmpty()` on `errors` here?
</blockquote></details>

Done.

---

*[analyzer/src/main/kotlin/managers/Gradle.kt, line 113 at r6](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/102#-L-abDbw96uQoJCQ8ROe:-L-agWUSIDDPph91xXJO:b-896fix) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/48b468314bb3bd4e2b70543bce730eccef39f9e2/analyzer/src/main/kotlin/managers/Gradle.kt#L113)):*
<details><summary><i>Previously, sschuberth (Sebastian Schuberth) wrote…</i></summary><blockquote>

Should this say "for Gradle project"? Also, this sounds as if you were listing Gradle projects. maybe invert the sentence and say something like "This Gradle project uses the following Maven repositories"?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/102)*

**Comment by sschuberth** [comment]
Reviewed 6 of 6 files at r7, 3 of 3 files at r8, 3 of 3 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/102)*

**Pull request merged**
