### PR TITLE
Upgrade Gradle to version 6.2

### PR DESCRIPTION
**Pull request by mnonnenmacher**
For the release notes see:
https://docs.gradle.org/6.2/release-notes.html

### CODE REVIEW

**Comment by mnonnenmacher** [comment]
> BTW, what do you think about switching to the `bin` distribution in the future to save some download time for fresh (Docker) builds?

Could Docker run `./gradlew wrapper --distribution-type BIN` before building? I would not like to have to manually switch to the `ALL` distribution locally on demand.

**Comment by sschuberth** [comment]
> I would not like to have to manually switch to the `ALL` distribution locally on demand.

Me neither. My question boils down to: Do we still have a need (for local development) to use the `all` distribution at all, or would we be fine with `bin` in any case?

**Comment by mnonnenmacher** [comment]
> Me neither. My question boils down to: Do we still have a need (for local development) to use the `all` distribution at all, or would we be fine with `bin` in any case?

I very rarely do changes in the Gradle files that require the sources, so yes, it would probably be fine to manually switch then. But I would still to prefer to switch the distribution in the the Dockerfile. The command I posted above will probably not help as it would download the `ALL` distribution first, but a simple `sed` line could also do the trick.

**Comment by sschuberth** [comment]
> but a simple `sed` line could also do the trick.

Right, but that does not really sound like a clean solution to me. I'll leave things as-is for now.

**Pull request merged**
