### PR TITLE
Helper-cli: Describe the parameters of several commands.

### PR DESCRIPTION
**Pull request by fviernau**
#1817

### CODE REVIEW

**Comment by sschuberth** [comment]
Nit: I'd prefer to have "param" spelled out as "parameter" in all commit messages.

**Comment by sschuberth** [comment]
Unrelated, but I just realized you're using `converter = FileConverter::class` in some but not all cases where the parameter is a file. Is it ever needed to specify it explicitly?

**Comment by fviernau** [comment]
> Unrelated, but I just realized you're using `converter = FileConverter::class` in some but not all cases where the parameter is a file. Is it ever needed to specify it explicitly?

Interresting, I'm not 100% sure IIRC but I think it is needed for `parameters` but not for `options`.
I hope the terminology is not clear here, e.g. `parameter == unnamed`. Let me double check if it is really needed. I will file a PR if necessary.

**Comment by fviernau** [comment]
> Interresting, I'm not 100% sure IIRC but I think it is needed for `parameters` but not for `options`.
> I hope the terminology is not too unclear here, e.g. `parameter == unnamed, option == named `. Let me double check if it is really needed. I will file a PR if necessary.

@sschuberth I just verified successfully that my above explanation was correct, e.g. without the converter set explicitly one gets the following (for un-namend parameter): 
```
Exception in thread "main" com.beust.jcommander.ParameterException: Could not invoke null
    Reason: Can not set java.io.File field com.here.ort.helper.commands.SortRepositoryConfigurationCommand.repositoryConfigurationFile to java.lang.String

```

**Pull request merged**
