### PR TITLE
Maven artifact download URLs and hashes

### PR DESCRIPTION
**Pull request by mnonnenmacher**
Search remote repositories for the download URLs and hashes of maven artifacts and source artifacts.

---
This change is [Reviewable](https://reviewable.io/reviews/heremaps/oss-review-toolkit/80)

### CODE REVIEW

**Comment by mnonnenmacher** [comment]
@sschuberth: I'd like to get feedback about the model changes in the first two commits before I start fixing the test fixtures, to avoid doing it multiple times.

**Comment by sschuberth** [comment]
Reviewed 7 of 7 files at r1, 6 of 6 files at r2.
Review status: 6 of 9 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/80)*

**Comment by sschuberth** [comment]
Reviewed 42 of 42 files at r3.
Review status: 1 of 44 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/80)*

**Comment by sschuberth** [comment]
Reviewed 41 of 41 files at r4.
Review status: 36 of 44 files reviewed at latest revision, 2 unresolved discussions.

---

*[analyzer/src/main/kotlin/managers/NPM.kt, line 254 at r4](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/80#-L-Vday98QFbg8wrnrZv:-L-Vday98QFbg8wrnrZw:b87krnx) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/497085038347a7b26c8fe51b4168dbd344fd67b4/analyzer/src/main/kotlin/managers/NPM.kt#L254)):*
> ```Kotlin
>                             hashAlgorithm = hashAlgorithm
>                     ),
>                     sourceArtifact = RemoteArtifact(
> ```

This should be `sourceArtifact = RemoteArtifact.createEmpty()`.

---

*[analyzer/src/main/kotlin/managers/PIP.kt, line 247 at r4](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/80#-L-Vdp2yobxGtmHJPnTf:-L-Vdp2yobxGtmHJPnTg:b87krnx) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/497085038347a7b26c8fe51b4168dbd344fd67b4/analyzer/src/main/kotlin/managers/PIP.kt#L247)):*
> ```Kotlin
>                                     hashAlgorithm = "MD5"
>                             ),
>                             sourceArtifact = RemoteArtifact(
> ```

This should be `sourceArtifact = RemoteArtifact.createEmpty()`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/80)*

**Comment by sschuberth** [comment]
Reviewed 1 of 1 files at r5, 7 of 7 files at r6.
Review status: 38 of 44 files reviewed at latest revision, 6 unresolved discussions.

---

*[analyzer/src/main/kotlin/MavenSupport.kt, line 131 at r6](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/80#-L-VeQawM7DWwvKjqxW8:-L-VeQaxEQcTrlR8gzUA:b-qc7ny9) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/278172f4d6e2d015ddf9236e68864cecd8b9f03f/analyzer/src/main/kotlin/MavenSupport.kt#L131)):*
> ```Kotlin
>         val transporterProvider = container.lookup(TransporterProvider::class.java, "default")
> 
>         // Create artifact descriptor to get list of repositories from the related POM file.
> ```

... an artifact ... the list ...

---

*[analyzer/src/main/kotlin/MavenSupport.kt, line 135 at r6](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/80#-L-VedELf2NTfZi7XAYF:-L-VedEMkGw1SdWGrM2D:btd4cpq) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/278172f4d6e2d015ddf9236e68864cecd8b9f03f/analyzer/src/main/kotlin/MavenSupport.kt#L135)):*
> ```Kotlin
>         val artifactDescriptorResult = repoSystem
>                 .readArtifactDescriptor(repositorySystemSession, artifactDescriptorRequest)
>         log.debug { "Found potential repositories for $artifact: ${artifactDescriptorResult.repositories}" }
> ```

Single-quote `$artifact` here? (If it might contain spaces.)

Similar below.

---

*[analyzer/src/main/kotlin/MavenSupport.kt, line 194 at r6](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/80#-L-VfHmq0hO0LO3uTTsv:-L-VfHmq0hO0LO3uTTsw:b-g8p49j) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/278172f4d6e2d015ddf9236e68864cecd8b9f03f/analyzer/src/main/kotlin/MavenSupport.kt#L194)):*
> ```Kotlin
>                     log.warn { "Could not get checksum for $artifact: ${e.message}" }
> 
>                     ""
> ```

Maybe add a comment like `// Fall back to an empty checksum string.` here? Otherwise the quotes might look a bit lost and can be easily overlooked.

This makes me also notice that we now use both "checksum" and "hash" terms. Should we switch to "checksum" in our model, too, as that seems to be the more generic term (see https://stackoverflow.com/a/460581/1127485)?

---

*[analyzer/src/main/kotlin/MavenSupport.kt, line 211 at r6](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/80#-L-Vg6xlPALi4SAy23dL:-L-Vg6xmdpngQJByk7J6:bipqw8t) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/278172f4d6e2d015ddf9236e68864cecd8b9f03f/analyzer/src/main/kotlin/MavenSupport.kt#L211)):*
> ```Kotlin
>         log.info { "Could not receive data about remote artifact $artifact." }
> 
>         return RemoteArtifact("", "", "")
> ```

Use `RemoteArtifact.createEmpty()`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/80)*

**Comment by sschuberth** [comment]
Reviewed 6 of 6 files at r7.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/80)*

**Comment by mnonnenmacher** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[analyzer/src/main/kotlin/MavenSupport.kt, line 131 at r6](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/80#-L-VeQawM7DWwvKjqxW8:-L-VjJ1yN7zoKwW-DL4K:b-896fix) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/278172f4d6e2d015ddf9236e68864cecd8b9f03f/analyzer/src/main/kotlin/MavenSupport.kt#L131)):*
<details><summary><i>Previously, sschuberth (Sebastian Schuberth) wrote…</i></summary><blockquote>

... an artifact ... the list ...
</blockquote></details>

Done.

---

*[analyzer/src/main/kotlin/MavenSupport.kt, line 135 at r6](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/80#-L-VedELf2NTfZi7XAYF:-L-VjadcZPVCqXA1lP4g:bpnikhy) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/278172f4d6e2d015ddf9236e68864cecd8b9f03f/analyzer/src/main/kotlin/MavenSupport.kt#L135)):*
<details><summary><i>Previously, sschuberth (Sebastian Schuberth) wrote…</i></summary><blockquote>

Single-quote `$artifact` here? (If it might contain spaces.)

Similar below.
</blockquote></details>

Done. It shouldn't contain spaces, but it's still better for readabililty.

---

*[analyzer/src/main/kotlin/MavenSupport.kt, line 194 at r6](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/80#-L-VfHmq0hO0LO3uTTsv:-L-VjlZGURw0dcYHYivZ:bcbkag4) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/278172f4d6e2d015ddf9236e68864cecd8b9f03f/analyzer/src/main/kotlin/MavenSupport.kt#L194)):*
<details><summary><i>Previously, sschuberth (Sebastian Schuberth) wrote…</i></summary><blockquote>

Maybe add a comment like `// Fall back to an empty checksum string.` here? Otherwise the quotes might look a bit lost and can be easily overlooked.

This makes me also notice that we now use both "checksum" and "hash" terms. Should we switch to "checksum" in our model, too, as that seems to be the more generic term (see https://stackoverflow.com/a/460581/1127485)?
</blockquote></details>

Done. I agree with the renaming to checksum.

---

*[analyzer/src/main/kotlin/MavenSupport.kt, line 211 at r6](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/80#-L-Vg6xlPALi4SAy23dL:-L-Vk7_RKd5efJApNoRP:b-896fix) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/278172f4d6e2d015ddf9236e68864cecd8b9f03f/analyzer/src/main/kotlin/MavenSupport.kt#L211)):*
<details><summary><i>Previously, sschuberth (Sebastian Schuberth) wrote…</i></summary><blockquote>

Use `RemoteArtifact.createEmpty()`?
</blockquote></details>

Done.

---

*[analyzer/src/main/kotlin/managers/NPM.kt, line 254 at r4](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/80#-L-Vday98QFbg8wrnrZv:-L-VkKwp57gXnJifutVE:b-896fix) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/497085038347a7b26c8fe51b4168dbd344fd67b4/analyzer/src/main/kotlin/managers/NPM.kt#L254)):*
<details><summary><i>Previously, sschuberth (Sebastian Schuberth) wrote…</i></summary><blockquote>

This should be `sourceArtifact = RemoteArtifact.createEmpty()`.
</blockquote></details>

Done.

---

*[analyzer/src/main/kotlin/managers/PIP.kt, line 247 at r4](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/80#-L-Vdp2yobxGtmHJPnTf:-L-VkPeCMMovzHwNxUqn:b-896fix) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/497085038347a7b26c8fe51b4168dbd344fd67b4/analyzer/src/main/kotlin/managers/PIP.kt#L247)):*
<details><summary><i>Previously, sschuberth (Sebastian Schuberth) wrote…</i></summary><blockquote>

This should be `sourceArtifact = RemoteArtifact.createEmpty()`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/80)*

**Comment by sschuberth** [comment]
Reviewed 3 of 3 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/80)*

**Pull request merged**
