### PR TITLE
Improvements to splitting VCS URLs

### PR DESCRIPTION
**Pull request by sschuberth**
Please have a look at the individual commit messages for the details.

---
This change is [Reviewable](https://reviewable.io/reviews/heremaps/oss-review-toolkit/109)

### CODE REVIEW

**Comment by mnonnenmacher** [comment]
Reviewed 1 of 1 files at r1, 4 of 4 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, 2 of 2 files at r6, 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[downloader/src/main/kotlin/VersionControlSystem.kt, line 104 at r5](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/109#-L-g5xZzZHt2AG-VaYI4:-L-g5x_0Ogm_qMkdREy0:b3ne4i9) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/8a7c878dca62bd620357fa6a3a0d8271867f87dd/downloader/src/main/kotlin/VersionControlSystem.kt#L104)):*
> ```Kotlin
> 
>                 return VcsInfo("git", url, revision, path)
>             }
> ```

We should also have a test that proves that this works for projects called "blob" or "tree".

---

*[downloader/src/main/kotlin/VersionControlSystem.kt, line 104 at r7](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/109#-L-g6kMgUJJKn5Rk-Xrn:-L-g6kMgUJJKn5Rk-Xro:be6m4je) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/bcdc9c458e998b58b235dc0a28cb550782a66977/downloader/src/main/kotlin/VersionControlSystem.kt#L104)):*
> ```Kotlin
>                     }
> 
>                     return VcsInfo("Git", url, revision, path)
> ```

No return required here, should be either inside or outside of when, but not both.

---

*[downloader/src/main/kotlin/VersionControlSystem.kt, line 132 at r7](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/109#-L-g6n17qgue6ZaCGb5l:-L-g6n17qgue6ZaCGb5m:be6m4je) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/bcdc9c458e998b58b235dc0a28cb550782a66977/downloader/src/main/kotlin/VersionControlSystem.kt#L132)):*
> ```Kotlin
>                         url += ".git"
>                     }
>                     return VcsInfo(provider, url, revision, path)
> ```

No return required here, should be either inside or outside of when, but not both.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/109)*

**Comment by sschuberth** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[downloader/src/main/kotlin/VersionControlSystem.kt, line 104 at r5](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/109#-L-g5xZzZHt2AG-VaYI4:-L-g8yDd6Em-lzsx_KUw:b-896fix) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/8a7c878dca62bd620357fa6a3a0d8271867f87dd/downloader/src/main/kotlin/VersionControlSystem.kt#L104)):*
<details><summary><i>Previously, mnonnenmacher (Martin Nonnenmacher) wrote…</i></summary><blockquote>

We should also have a test that proves that this works for projects called "blob" or "tree".
</blockquote></details>

Done.

---

*[downloader/src/main/kotlin/VersionControlSystem.kt, line 104 at r7](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/109#-L-g6kMgUJJKn5Rk-Xrn:-L-g99JCPt_Dk1lnpvEv:by3e9qu) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/bcdc9c458e998b58b235dc0a28cb550782a66977/downloader/src/main/kotlin/VersionControlSystem.kt#L104)):*
<details><summary><i>Previously, mnonnenmacher (Martin Nonnenmacher) wrote…</i></summary><blockquote>

No return required here, should be either inside or outside of when, but not both.
</blockquote></details>

There is no `when` in this commit just yet, it only comes with the commit introducing Bitbucket support.

---

*[downloader/src/main/kotlin/VersionControlSystem.kt, line 132 at r7](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/109#-L-g6n17qgue6ZaCGb5l:-L-g9KaBqt6sPtPKeceo:brrue0u) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/bcdc9c458e998b58b235dc0a28cb550782a66977/downloader/src/main/kotlin/VersionControlSystem.kt#L132)):*
<details><summary><i>Previously, mnonnenmacher (Martin Nonnenmacher) wrote…</i></summary><blockquote>

No return required here, should be either inside or outside of when, but not both.
</blockquote></details>

See above, there is one `return` inside the `if`, and this one outside in the end.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/109)*

**Comment by mnonnenmacher** [comment]
Reviewed 2 of 2 files at r8, 2 of 2 files at r9.
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[downloader/src/main/kotlin/VersionControlSystem.kt, line 104 at r7](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/109#-L-g6kMgUJJKn5Rk-Xrn:-L-gD3fkCRVpm9i6WwAw:b99px7h) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/bcdc9c458e998b58b235dc0a28cb550782a66977/downloader/src/main/kotlin/VersionControlSystem.kt#L104)):*
<details><summary><i>Previously, sschuberth (Sebastian Schuberth) wrote…</i></summary><blockquote>

There is no `when` in this commit just yet, it only comes with the commit introducing Bitbucket support.
</blockquote></details>

Weird, that's where I put this and the below comments. Reviewable must have messed it up somehow, I guess because it is showing comments for all revisions where the file was edited.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/109)*

**Comment by sschuberth** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[downloader/src/main/kotlin/VersionControlSystem.kt, line 104 at r7](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/109#-L-g6kMgUJJKn5Rk-Xrn:-L-gF6mTPQuAEuGRv6Mo:b-ugxv5v) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/bcdc9c458e998b58b235dc0a28cb550782a66977/downloader/src/main/kotlin/VersionControlSystem.kt#L104)):*
<details><summary><i>Previously, mnonnenmacher (Martin Nonnenmacher) wrote…</i></summary><blockquote>

Weird, that's where I put this and the below comments. Reviewable must have messed it up somehow, I guess because it is showing comments for all revisions where the file was edited.
</blockquote></details>

Anyway, I now see what you mean and have just fixed it!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/109)*

**Comment by mnonnenmacher** [comment]
Reviewed 2 of 2 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/109)*

**Pull request merged**
