### PR TITLE
Yarn: Upgrade to version 1.12.1

### PR DESCRIPTION
**Pull request by fviernau**
This change is [Reviewable](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1009)

### CODE REVIEW

**Comment by sschuberth** [comment]
Why? What's the rationale? Is there a specific reason to do so? Please add a brief explanation about that to the commit message, and please also sign it off.

**Comment by haraldF** [comment]
yarn changed the lock file format and added stricter SHA checks, which we have in one of the projects we want to scan. To prevent overwriting our yarn.lock with oder versions, we require yarn >= 10.x, thus, the OSS scanner refuses to scan.

**Comment by sschuberth** [comment]
@tsteenbe, I just had restarted AppVeyor CI for this to see it complete... please do not merge without CI checks succeeding (on all platforms) without providing a proper rationale.

**Comment by tsteenbe** [comment]
I though we still had AppVeyor CI issues so it was OK to merge without AppVeyor passing.

**Comment by sschuberth** [comment]
That's what the log is for to check 😉

**Pull request merged**
