### PR TITLE
Fix k9mail tests

### PR DESCRIPTION
**Pull request by mnonnenmacher**
See the individual commit messages for details.

---
This change is [Reviewable](https://reviewable.io/reviews/heremaps/oss-review-toolkit/140)

### CODE REVIEW

**Comment by sschuberth** [comment]
@mnonnenmacher I had to [fix the test baseline in master](https://github.com/heremaps/oss-review-toolkit/commit/e4ed1d659041b579db2a01f1d4739bb5bc71dec8) yesterday. Please rebase your branch onto master to retrigger CI.

**Comment by sschuberth** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 6 of 6 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[analyzer/src/funTest/assets/projects/external/gradle-expected-results/k9-mail/plugins/HoloColorPicker/build-gradle-dependencies.yml, line 90 at r4](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/140#-L0EBCA4LCct-TAXpfEu:-L0EBCA5WvKSsn5R4kS6:bayuydd) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/8a8d050a32e5558215a62b380703b1e959c77b3f/analyzer/src/funTest/assets/projects/external/gradle-expected-results/k9-mail/plugins/HoloColorPicker/build-gradle-dependencies.yml#L90)):*
> ```YAML
>       dependencies: []
>       errors:
>       - "Unresolved: ModuleVersionNotFoundException: Could not find org.jacoco:org.jacoco.agent:0.7.5.201505241946.\n\
> ```

Are these errors expected? In any case, we should have you personal absolute home path hard-coded here.

---

*[analyzer/src/main/kotlin/MavenSupport.kt, line 259 at r1](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/140#-L0EAXsCY5OYVXmckltU:-L0EAXsCY5OYVXmckltV:b5jfy63) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/7b3620275898b4c3c0120375981a7bd947cc1030/analyzer/src/main/kotlin/MavenSupport.kt#L259)):*
> ```Kotlin
>         val projectBuildingRequest = createProjectBuildingRequest(true)
> 
>         projectBuildingRequest.remoteRepositories = repositories.map {
> ```

Just for my information, is this the correct fix for what I played with at https://github.com/heremaps/oss-review-toolkit/commit/ad3a58ecbbb79c0d3864c3f452e571175d6b1c1e#diff-212b3ddb7fb9e4c47dcafe589c826bafR142 ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/140)*

**Comment by mnonnenmacher** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[analyzer/src/funTest/assets/projects/external/gradle-expected-results/k9-mail/plugins/HoloColorPicker/build-gradle-dependencies.yml, line 90 at r4](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/140#-L0EBCA4LCct-TAXpfEu:-L0EDugSbkJp9WYpGmGJ:b-ijmx08) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/8a8d050a32e5558215a62b380703b1e959c77b3f/analyzer/src/funTest/assets/projects/external/gradle-expected-results/k9-mail/plugins/HoloColorPicker/build-gradle-dependencies.yml#L90)):*
<details><summary><i>Previously, sschuberth (Sebastian Schuberth) wrote…</i></summary><blockquote>

Are these errors expected? In any case, we should have you personal absolute home path hard-coded here.
</blockquote></details>

Yes, they are still expected. Thanks for finding the home paths. I think we cannot really fix this, as these are the plain messages from the exceptions, so I will patch the results in the test code as a workaround.

---

*[analyzer/src/main/kotlin/MavenSupport.kt, line 259 at r1](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/140#-L0EAXsCY5OYVXmckltU:-L0EDci64pOpZXH-E2Qh:b-bl0sz9) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/7b3620275898b4c3c0120375981a7bd947cc1030/analyzer/src/main/kotlin/MavenSupport.kt#L259)):*
<details><summary><i>Previously, sschuberth (Sebastian Schuberth) wrote…</i></summary><blockquote>

Just for my information, is this the correct fix for what I played with at https://github.com/heremaps/oss-review-toolkit/commit/ad3a58ecbbb79c0d3864c3f452e571175d6b1c1e#diff-212b3ddb7fb9e4c47dcafe589c826bafR142 ?
</blockquote></details>

It is related, but maybe something similar to your change still needs to be done. I will see when I continue testing with more projects.
This fixes an issue when building the Maven project for the artifact and not all required POM files could be found. In the step below when we are looking for the actual artifacts like e.g. a sources jar there might still be repos missing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/140)*

**Comment by mnonnenmacher** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[analyzer/src/funTest/assets/projects/external/gradle-expected-results/k9-mail/plugins/HoloColorPicker/build-gradle-dependencies.yml, line 90 at r4](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/140#-L0EBCA4LCct-TAXpfEu:-L0EI8Xw93y_orlW-JJ5:bgjw8fg) ([raw file](https://github.com/heremaps/oss-review-toolkit/blob/8a8d050a32e5558215a62b380703b1e959c77b3f/analyzer/src/funTest/assets/projects/external/gradle-expected-results/k9-mail/plugins/HoloColorPicker/build-gradle-dependencies.yml#L90)):*
<details><summary><i>Previously, mnonnenmacher (Martin Nonnenmacher) wrote…</i></summary><blockquote>

Yes, they are still expected. Thanks for finding the home paths. I think we cannot really fix this, as these are the plain messages from the exceptions, so I will patch the results in the test code as a workaround.
</blockquote></details>

Actually I cannot find a good way to workaround this, so I will rather work on fixing the root causes of the errors, but this might take some more time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/heremaps/oss-review-toolkit/140)*

**Comment by mnonnenmacher** [comment]
I decided to do a general refactoring of those tests in a different PR instead.

**Pull request closed without merging**
