### PR TITLE
Independent docker build

### PR DESCRIPTION
**Pull request by sweetca**
simplify docker build process

---
This change is [Reviewable](https://reviewable.io/reviews/heremaps/oss-review-toolkit/1581)

### CODE REVIEW

**Comment by sschuberth** [comment]
Thanks for the contribution. Would you mind explaining how this is simpler than running `./gradlew cli:dockerBuildImage` and then `docker run ort`? Also, please note that there are other docker-related branches being worked on currently (in particular, the `jenkinsfile` branch), so you may want to have a look at them, to see whether these would also solve your issue (whichever that is).

**Comment by sweetca** [comment]
> Thanks for the contribution. Would you mind explaining how this is simpler than running `./gradlew cli:dockerBuildImage` and then `docker run ort`? Also, please note that there are other docker-related branches being worked on currently (in particular, the `jenkinsfile` branch), so you may want to have a look at them, to see whether these would also solve your issue (whichever that is).

thanks for reply @sschuberth 
This workflow is better in case if you do not want install all build required software like git|yarn|node|java onto your local machine.
This slightly different logic: we build `oss-review-toolkit` inside docker. This give us full environment independence.
When developers will have this proposed solution - to start locally `oss-review-toolkit` they will need do 1 steps & docker locally:
```cd ~/oss-review-toolkit && docker build -t heremaps/oss-review-toolkit:latest .```
Thats more simple than:
- install java
- install node js
- install yarn
- match versions of them
- setup env variables for it
Also lets say that some of them have already yarn|java|npm|node and version does not match `oss-review-toolkit` build requirements. This bring more pain for start it locally.

**Comment by sweetca** [comment]
@sschuberth added license header into `Dockerfile`

**Comment by sschuberth** [comment]
Note that for `./gradlew cli:dockerBuildImage` to work you only need a JDK and Yarn, everything else is in [cli/docker/Dockerfile](https://github.com/heremaps/oss-review-toolkit/blob/bdfd9e48a50449e15af0b93bc2d8f0d7a7b6b2c9/cli/docker/Dockerfile).

However, I get your point in that the above is a `Dockerfile` for *running* ORT, but developers may want to have a `Dockerfile` for *building* ORT (and people seem to mix this up, also see issue https://github.com/heremaps/oss-review-toolkit/issues/1357). This is exactly the issue being currently addressed in the [jenkinsfile](https://github.com/heremaps/oss-review-toolkit/tree/jenkinsfile/docker) branch which will feature three separate `Dockerfiles` for building, testing and running ORT, respectively.

**Comment by sweetca** [comment]
> > Thanks for the contribution. Would you mind explaining how this is simpler than running `./gradlew cli:dockerBuildImage` and then `docker run ort`? Also, please note that there are other docker-related branches being worked on currently (in particular, the `jenkinsfile` branch), so you may want to have a look at them, to see whether these would also solve your issue (whichever that is).
> 
> thanks for reply @sschuberth
> This workflow is better in case if you do not want install all build required software like git|yarn|node|java onto your local machine.
> This slightly different logic: we build `oss-review-toolkit` inside docker. This give us full environment independence.
> When developers will have this proposed solution - to start locally `oss-review-toolkit` they will need do 1 steps & docker locally:
> `cd ~/oss-review-toolkit && docker build -t heremaps/oss-review-toolkit:latest .`
> Thats more simple than:
> 
> * install java
> * install node js
> * install yarn
> * match versions of them
> * setup env variables for it
>   Also lets say that some of developers have already yarn|java|npm|node and version does not match `oss-review-toolkit` build requirements. This bring more pain for start it locally.

@sschuberth sorry for worries, but this flow may be alternative for 
`https://github.com/heremaps/oss-review-toolkit/blob/master/cli/docker/Dockerfile`
seams like not all developers required such dockerization style.

**Comment by sweetca** [comment]
> nch which will feature three

@sschuberth agreed, should I provide this PR into `jenkinsfile` as example?

**Comment by sweetca** [comment]
> Thanks for the contribution. Would you mind explaining how this is simpler than running `./gradlew cli:dockerBuildImage` and then `docker run ort`? Also, please note that there are other docker-related branches being worked on currently (in particular, the `jenkinsfile` branch), so you may want to have a look at them, to see whether these would also solve your issue (whichever that is).

@sschuberth agreed, should I provide this PR into jenkinsfile as example?

**Comment by sweetca** [comment]
> Note that for `./gradlew cli:dockerBuildImage` to work you only need a JDK and Yarn, everything else is in [cli/docker/Dockerfile](https://github.com/heremaps/oss-review-toolkit/blob/bdfd9e48a50449e15af0b93bc2d8f0d7a7b6b2c9/cli/docker/Dockerfile).
> 
> However, I get your point in that the above is a `Dockerfile` for _running_ ORT, but developers may want to have a `Dockerfile` for _building_ ORT (and people seem to mix this up, also see issue #1357). This is exactly the issue being currently addressed in the [jenkinsfile](https://github.com/heremaps/oss-review-toolkit/tree/jenkinsfile/docker) branch which will feature three separate `Dockerfiles` for building, testing and running ORT, respectively.

@sschuberth agreed, should I provide this PR into jenkinsfile as example?

**Comment by sschuberth** [comment]
> should I provide this PR into `jenkinsfile` as example?

No, please simply give me a few more days so I can finish the work on the `jenkins` branch and get it merged to `master`, and then please check whether that solution can fully replace your PR ans serves your needs.

**Comment by sschuberth** [comment]
Please see https://github.com/heremaps/oss-review-toolkit/pull/1589 for what I'm proposing instead.

**Comment by sschuberth** [comment]
@sweetca, the new Dockerfiles are now merged in master, and documentation to [build](https://github.com/heremaps/oss-review-toolkit#build-using-docker) and / or [run](https://github.com/heremaps/oss-review-toolkit#run-using-docker) ORT using Docker is available, too. Could you please check whether your PR still needed?

**Comment by sschuberth** [comment]
Closing this as an alternative solution was merged meanwhile. Feel free to reopen if you feel your use-case was not addressed by this.

**Pull request closed without merging**
